### ISSUE TITLE
crash on exampleGeometry

### ISSUE THREAD

**Issue by nicolaihess** [pharo-graphics/Bloc#10]
Hi I tried to execute the exampleGeometry example, on both the all-in-one developer
wget -O- --no-check-certificate https://goo.gl/HQAPI5 | bash
and the vm/image artefact from jenkins. It crashes as son as I execute teh exampl
[crash.txt](https://github.com/pharo-graphics/Bloc/files/737375/crash.txt)

e
on:
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18
DISTRIB_CODENAME=sarah
DISTRIB_DESCRIPTION="Linux Mint 18 Sarah"
Linux phobos 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:00:59 UTC 2016 i686 athlon i686 GNU/Linux

**Comment by syrel** [comment]
Thanks for bug report!

Moz2D seams to be unstable on Linux distros except Ubuntu 14/16.
We will soon move Bloc to Cairo+Freetype2 and make Moz2D backend optional and mark it as Beta.

**Comment by girba** [comment]
This should work now. If it's still an issue, please reopen the issue.
