### ISSUE TITLE
testDeferredAction kills this image.

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#101]
testDeferredAction
	| runFlag processflag |
	self skip.
	"This test can only be run once"
	processflag := runFlag := false.
	BlUniverse reset.
	BlUniverse default
		start;
		defer: [ runFlag := true.
			processflag := BlUniverse default isUIProcess  ].
	(Delay forSeconds: 1) wait.
	BlUniverse reset.
	self assert: runFlag description:'the deferred action should be run'.
	self assert: processflag description:'the deferred action should be run within the UI Process'.

**Comment by tinchodias** [comment]
I commented about it today in https://github.com/pharo-graphics/Bloc/issues/89

**Comment by syrel** [comment]
You should remove BlUniverse, it was replaced by BlParallelUniverse and was kept in case there were external users

**Comment by syrel** [comment]
We made sure that BlUniverse is not referenced directly for deferred tasks and instead everything is handled through a space

**Comment by tinchodias** [comment]
Thanks. In the code of my image, it's referenced here (apart from the test):
```smalltalk
availableCanvasBuilderClasses
  "Return all available sparta canvas builder classes sorted by their priority"
  <return: #Collection>
  
  ^ ((BlSpartaCanvasBuilder allSubclasses select: [ :aBuilderClass | aBuilderClass isSupported ])
    select: [ :aBuilderClass | 
      BlHostRendererSurface allSurfaces anySatisfy: [ :aSurfaceClass |
        (aSurfaceClass supportedBy: aBuilderClass) and: [ aSurfaceClass supportedBy: BlUniverse default host ] ] ])
    sort: [ :a :b | a priority < b priority ]
```
and debugging the expression `BlUniverse default host` it steps into:
```smalltalk
BlUniverse>>
host
	^ host ifNil: [ BlHost pickHost ]
```
host is nil, so it answers the default value... then I guess we could replace `BlUniverse default host` by `BlHost pickHost`.

**Comment by syrel** [comment]
yes

**Comment by tinchodias** [comment]
I tried to keep an equivalent of the test instead of just removing it, and understand more of this key class.
I observed in the following method that a (parallel) universe has a pulse with 3 parts:
1. deferred
2. pulse of each spaces 
3. postponed

```
BlParallelUniverse >>
pulseSynchronously
	"deferred actions must be run before spaces"
	[
		self tryToRunDeferredActions.
		spaceManager do: [ :eachSpace | eachSpace pulse ]
	] ensure: [ self tryToRunPostponedActions ]
```

and played with this test that couldn't make work:
```
BlSpaceTest >>
testDefer
	| queue |
	queue := SharedQueue new.

	space universe defer: [ queue nextPut: 1 ].
	space enqueueTask: (BlTaskAction new action: [ queue nextPut: 2 ]; yourself).
	space universe postpone: [ queue nextPut: 3 ].

	self assert: queue isEmpty.
	space universe pulse.
	self assert: queue contents equals: #(1 2 3).
```

**Comment by tinchodias** [comment]
But anyway, we can close this issue via commit c8ab99c

**Comment by Ducasse** [comment]
Perfect!
