### ISSUE TITLE
BlElement has gtDisplayOn: 

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#105]
```
gtDisplayOn: aStream
	self printOn: aStream
```

**Comment by tinchodias** [comment]
Exactly the same implementation as in its direct superclass, Object. 

So I'm removed it in https://github.com/pharo-graphics/Bloc/commit/85aa4530b9609a420b509c7cbccf06768fa20c31

**Comment by tinchodias** [comment]
I don't know the history of this selector. There are 31 implementors in current Pharo 9. The answer of `#gtDisplayOn: implementors collect: #origin` is:

an OrderedCollection [31 items] (ClySpotterModel Collection CompiledBlock CompiledMethod FileReference GLMAction GLMTransmission GTPlayPage GTSelector GTSpotter GTSpotterCandidateLink GTSpotterPragmaBasedProcessor GTSpotterProcessorLink HelpTopic IceProxyMCVersionInfo KMCategory KMKeymap MCDirectoryRepository MCHttpRepository MCPackage MCPackageManager MCRepository MCVersionInfo MCWorkingCopy MessageTally MethodChunk Object Pragma SocketAddress String Text)

**Comment by tinchodias** [comment]
Packages are:

a Set [8 items] (#'GT-SpotterExtensions-Core' #'GT-Spotter' #'GT-Playground' #Iceberg #'Glamour-Core' #'Calypso-SystemPlugins-Spotter' #'GT-InspectorExtensions-Core' #'GT-Inspector')

obtained with: `#gtDisplayOn: implementors collect: [ :each | each package name ] as: Set`

**Comment by tinchodias** [comment]
From the code loaded by NewBloc, there was only one more occurrence of `gtDisplayOn:`and it was also the same implementation as in the superclasses.

So, Ii removed it in https://github.com/pharo-graphics/Bloc/commit/1b2e218204decde83544e294bd1816c63d0881c1

**Comment by tinchodias** [comment]
We can close this issue now.
