### ISSUE TITLE
Evaluate use of read-only object support in P9

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Bloc#118]
There are 9 references to `BlImmutableObjectChangeError` that apparently could be replaced by this new feature available in Pharo 9.

Mentioned in #82

**Comment by tinchodias** [comment]
The rewriting wouldn't be direct. Take the example of `BlBorder`. There are 4 users of `BlImmutableObjectChangeError` there:

<img width="731" alt="Screen Shot 2021-03-05 at 19 34 20" src="https://user-images.githubusercontent.com/3044265/110181084-cc196380-7de9-11eb-92f3-9cb584a437c4.png">

I see in the implementation that it is not that the entire instance of `BlBorder` becomes read-only but the individual slot (opacity, paint, style, width). When opacity is set, then it can't be changed but the paint has permission to be set, still.

If we can do it for the whole border instance like this and should work for all the slots together:
```
aBorder := BlBorder paint: Color blue width: 5.
aBorder beReadOnlyObject.
```

**Comment by Ducasse** [comment]
Martin ready only is super costly I would not use it.

**Comment by tinchodias** [comment]
Ah, I didn't know that. Well, let's close it.
