### ISSUE TITLE
Fix OSWindow host

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Bloc#119]
1. Load the 2 packages OSWindow via Iceberg
2. Select the host in System Preferences
3. Open an element in a space. For example:

```smalltalk
| space elt |
space := BlSpace new.
elt := BlElement new
			geometry: BlCircleGeometry new;
			border: (BlBorder paint: Color blue width: 5);
			background: Color red;
			when: BlClickEvent do: [ :anEvent |
				anEvent consumed: true.
				self inform: 'click' ];
			yourself.
space addChild: elt.
space show.
```

You will get an error

**Comment by tinchodias** [comment]
Warning sample:

<img width="375" alt="Screen Shot 2021-03-08 at 17 24 20" src="https://user-images.githubusercontent.com/3044265/110377407-20fbea80-8033-11eb-8894-74295725508e.png">

Assertion failure at SDL_GL_MakeCurrent_REAL (/Users/travis/build/OpenSmalltalk/opensmalltalk-vm/build.macos64x64/pharo.cog.spur/build/third-party/SDL2-2.0.7/src/video/SDL_video.c:3427), triggered 5 times:
'window && window->magic == &_this->window_magic'

**Comment by Ducasse** [comment]
Super sweet! Lovely!

**Comment by Ducasse** [comment]
Why should we load the two packages?

**Comment by tinchodias** [comment]
Ah, sorry. After pushing the commit I added the Baselines so now it's not needed anymore to laod packages.
