### ISSUE TITLE
Why BlElementVisuals are not defined as a sharedPools

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#124]
I do not get the point to have a singleton. 
BlElementVisuals is basically a bunch of class variables.

**Comment by Ducasse** [comment]
I do not understand either 

```
BlDefaultVisuals >> opacity: aNumber
	"Change the opacity and return new visuals to be used instead of the previous one (not necessarily a new instance)"
	<return: #BlElementVisuals>

	^ BlCustomVisuals new opacity: aNumber
```

So if I changed two elements what will happen? Since a new BlCustomVisuals will be returned.

**Comment by syrel** [comment]
https://en.m.wikipedia.org/wiki/Flyweight_pattern

**Comment by Ducasse** [comment]
Syrel I know what is a flyweigth, still I do not get this design.

**Comment by syrel** [comment]
I don’t understand what you don’t understand :) What is not clear for example in the following call chain:
BlElement>>#background:

If default visuals is a unique instance, there is really no other way to implement it. What do you think?

**Comment by syrel** [comment]
All new elements share the same instance of BlDefaultVisuals, which does not have any inst.vars. So if we want to set custom background we have to swap DefaultVisuals with CustomVisuals that stores custom background as an inst.var.

**Comment by Ducasse** [comment]
Too tired to think now.
I will come back to this point. Because it is still unclear.

**Comment by Ducasse** [comment]
May be you should read my lecture where I show how to share a given value by a set of instances while at the same time supporting instance specific value. - I thought it was online but it is not I have to look for it. 
In essence a class has a classvar and an instance var. the class var refers to the shared resources and at creation time the instance instance var is pointed to the class var and all the methods are just using the instance var and never refer to the classvar. If we want to have an instance specific resource: easy copy the shared resources, change it and plug in the instance instance var.

What I do not understand is the fact that a new instance of custom is created for any changes so I do not understand how I can have two customizations on the same visuals, since we new instance is returned by each setter. 

For the record this is not a flyweight.

**Comment by syrel** [comment]
Hi,
What you described is not memory efficient. Please, take a careful look at the difference between BlDefaultVisuals and BlCustomVisuals. Default visuals does not have any instance variables which is a huge advantage. Custom visuals do have inst vars which allows customization.

About new instances, if you look carefully you will see that when modified, custom visuals does not return a new instance, while default one does return (obviously).

**Comment by syrel** [comment]
BlDefaultVisuals is shared between many many elements, custom visuals are unique for each element

**Comment by syrel** [comment]
The goal of the Visuals is to share as much data between instances as possible. We could also create specific visuals that just has custom background or custom border, sharing the rest of properties with other elements. Look very flyweight to me!
```
In computer programming, flyweight is a software design pattern. A flyweight is an object that minimizes memory usage by sharing as much data as possible with other similar objects; it is a way to use objects in large numbers when a simple repeated representation would use an unacceptable amount of memory.
```

**Comment by Ducasse** [comment]
Ok if you believe I do not understand then you are right.
