### ISSUE TITLE
BlTextElement broken (test too)

### ISSUE THREAD

**Issue by darth-cheney** [pharo-graphics/Bloc#14]
Currently `BlTextElement` doesn't work at all, and neither does the `example` class message (though, curiously, the `exampleText` class message works fine).
  
I currently cannot get text to display at all in any `BlElement` or `BlSpace`.
  
The error is consistent ([here](https://gist.github.com/darth-cheney/1430353c427f1d26eea657d7a024d1a4) is a report from the stack trace after running `BlTextElement example`).
  
The top of the stack trace always has: 
```
SpText(Object)>>doesNotUnderstand: #lockDuring:
```

**Comment by syrel** [comment]
Was fixed in https://github.com/pharo-graphics/Bloc/commit/ecec389c6d5d12fe1b7a20cc5508db2045056041
