### ISSUE TITLE
Undeclared global reference to Trasncripter in BlocHost-Morphic extension to PharoCommonTools

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Bloc#141]
<img width="679" alt="Screen Shot 2021-04-26 at 18 30 38" src="https://user-images.githubusercontent.com/3044265/116159022-824c4b80-a6bd-11eb-8078-1e4e25c108e3.png">

```
PharoCommonTools>>
emergencyDebugger
	^ tools
		at: #emergencyDebugger
		ifAbsent: [ Transcripter ]
```

**Comment by tinchodias** [comment]
The only other implementor is:

```
DebuggerSettings class>>
emergencyDebugger

	^ self environment
		  at: #EDEmergencyDebugger
		  ifAbsent: [ DebuggerEmmergencyLogger new ]
```

**Comment by tinchodias** [comment]
The user in Bloc is:

```
BlBlocUIManager >>
onPrimitiveError: aString 
	| message |

	message := String
				streamContents: [:s | 
					| context |
					s nextPutAll: '*** System error handling failed ***'.
					s cr; nextPutAll: aString.
					context := thisContext sender sender.
					20
						timesRepeat: [context == nil
								ifFalse: [s cr; print: (context := context sender)]]].
	Smalltalk tools emergencyDebugger askForEmergencyEvaluatorOrExitWithText: message.
```

**Comment by tinchodias** [comment]
`DebuggerEmmergencyLogger` is just subclass of `Object`, and I don't read specification of what's the common API with `EDEmergencyDebugger`. But by browsing I detected the only selector in common: `debugError:fromSession:`.

Maybe `DebuggerSettings class >> emergencyDebugger` should say it in the comment. Opinion @Ducasse ?

**Comment by tinchodias** [comment]
In other words, I don't see an equivalent of `askForEmergencyEvaluatorOrExitWithText:` that receives only a string. I should ask to the debuggers' team.

**Comment by Ducasse** [comment]
I do not know we should ask Steven Costiou
