### ISSUE TITLE
BlSpace windows remove other dragged windows on "drop/release"

### ISSUE THREAD

**Issue by darth-cheney** [pharo-graphics/Bloc#15]
If I have an open `BlSpace` window and I drag another window (like a Playground) on top of it to make space, the Playground window will vanish. This happens with any Morphic display objects.
  
Note that the pointer must be over both the held window and the space window when released in order for this to happen.

**Comment by syrel** [comment]
Probably it is a feature :)
But we need to see if it makes sense to disable this behaviour for morphic windows
