### ISSUE TITLE
Move Geometries from Basic

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Bloc#155]
There are plenty of Bloc-Basic-XXXX tags, and geometries deserve one:

<img width="427" alt="Screen Shot 2021-06-09 at 16 26 12" src="https://user-images.githubusercontent.com/3044265/121424514-69cb8400-c93f-11eb-8a78-f70b373eeb85.png">

**Comment by tinchodias** [comment]
Additionally, `BlPloygon` could move to `Bloc-Basic-Deprecated` together with the other deprecated geometries.

**Comment by astares** [comment]
Remember that in Pharo we often use "Base" not "Basic" tag for the base functionality (primary classes) within a package

**Comment by tinchodias** [comment]
Hi, thanks for the comment.
I agree that geometries are basic in Bloc: any BlElement has one. But other "basic" classes do have their own tags, such as Events, Math, Space, Universe. In that context, I felt it is inconsistent that Geometries are in a grouping tag, too.

**Comment by tinchodias** [comment]
In other commit we can change from Basic to Base, as suggested by astares.
