### ISSUE TITLE
KeyboardKey should be used instead of BlKeyboardKey 

### ISSUE THREAD

**Issue by plantec** [pharo-graphics/Bloc#169]
It will allow BlKeyboardKey and BlMorphicKeyboardKeyTable deprecation.
Need to add some class methods to KeyboardKey to make Morphic host work properly

**Comment by tinchodias** [comment]
Was this closed by https://github.com/pharo-graphics/Bloc/pull/170 ?

**Comment by plantec** [comment]
ok for macOS, not sure in windows and linux.

**Comment by plantec** [comment]
it seems ok in windows and in linux now. I've tested with virtualbox. the editor has strange behavior in windows though.
