### ISSUE TITLE
Halt now freezes Pharo/Bloc-dev-1.0

### ISSUE THREAD

**Issue by plantec** [pharo-graphics/Bloc#173]
Linux Ubuntu
Pharo 11 lastest
Bloc 1.0

Halt now.

**Comment by plantec** [comment]
I certainly do something wrong. I've tried in Mac OS, same result.
I load newBloc with:
Metacello new
        baseline: 'NewBloc';
        repository: 'github://pharo-graphics/Bloc/src';
        load.
then, with Iceberg, checkout branch / origin - 1.0
then Halt now
then nothing

Maybe I've to send a magic invocation to something after checking out ?

**Comment by tinchodias** [comment]
On this branch, I renamed BaselineOfNewBloc to BaselineOfBloc.
May be only that?
I will try now, anyway... I have been working in old images and didn't install recently

**Comment by tinchodias** [comment]
<img width="1032" alt="Screen Shot 2022-05-03 at 07 48 58" src="https://user-images.githubusercontent.com/3044265/166447501-e090dfd4-2bc1-415c-95e0-70228e56bea0.png">

The only problem I had was dependency warning related to BlExamplesTest, and I pressed on Proceed twice.

My exact steps were:

1. On Mac, opened terminal and executed `curl https://get.pharo.org/100+vm | bash`
2. I opened and evaluate:
```
Metacello new
        baseline: 'Bloc';
        repository: 'github://pharo-graphics/Bloc/src';
        load.
```

**Comment by tinchodias** [comment]
Ooops, previous message is wrong: I didn't specify a branch to Metacello so it installed from master.

The correct script is:
```
Metacello new
        baseline: 'Bloc';
        repository: 'github://pharo-graphics/Bloc:dev-1.0/src';
        load.
```
I updated the install script on the README of dev-1.0 branch.

But I got an error related to keys:

<img width="1119" alt="Screen Shot 2022-05-03 at 07 58 22" src="https://user-images.githubusercontent.com/3044265/166448748-ad9d00bb-d144-493d-9b0f-8cd2c0d6f8ca.png">

**Comment by tinchodias** [comment]
To continue with the installation, I deleted inexistent key selectors (only locally on my image) and was asked about Merging or Loading Pharo-Beacon. I pressed on load, and after finishing load, I if Halt now and worked.

**Comment by tinchodias** [comment]
Sorry @plantec the keys error don't happen in Pharo 11, of course I should had use that image.

I enforced the install script so there is no need of human interaction (updated README too):

```
[ Metacello new
	baseline: 'Bloc';
	repository: 'github://pharo-graphics/Bloc:dev-1.0/src';
	onConflictUseIncoming;
	ignoreImage;
	load ]
		on: MCMergeOrLoadWarning
		do: [ :warning | warning load ]
```

**Comment by plantec** [comment]
thanks! it works.

**Comment by tinchodias** [comment]
@plantec Hi, I experienced today problems with halt as you described.
It is in Pharo 11, too.
I showed Pablo and he was trying to reproduce the issue.

**Comment by plantec** [comment]
arrrgh, i reopen the issue so.
thanks

**Comment by tinchodias** [comment]
Seems to be something in current Pharo 11. 

My steps:
I put a halt in a method involved in drawing in cairo, I execute a snippet with cmd+d. Obviously, my expectation is to see a debug window at the point of execution where I placed the halt, but the image becomes unresponsive (no cmd+, not any option).

**BUT** I found a workaround: use cmd+shift+d instead of cmd+d ("debug it"). When the debugged windows opens, I press Proceed, and then it stops at halt as I expected.

**Comment by tesonep** [comment]
I have tried loading in a clean P11 image
```
Metacello new
    baseline: 'BlocBenchs';
    repository: 'github://pharo-graphics/BlocBenchs/src';
    load.
```
And I don't have any issue, are you loading something else or doing something else @tinchodias

**Comment by tinchodias** [comment]
I didn't suffer this again. Did you, @plantec ?
Should we close again?
