### ISSUE TITLE
registerFacesOnMemory: send unknown message registerFace:

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#181]
registerFacesOnMemory: aByteArray 

	self freetypeLibrary
		fastReadFacesOnMemory: aByteArray
		do: [ :aFace :index |
			self registerFace: aFace entry: 
				(AeMemoryFaceEntry new
					bytes: aByteArray;
					index: index;
					yourself) ]

I was looking how the font are read then cached as methods on the subclasses of AeEmbeddedFontFile
It would be good to have a better comment in the Manager to explain how we can add / embed fonts.

Now the following method does not work because registerFace: does not exit.

**Comment by Ducasse** [comment]
Ok the method was registerFace:entry: and it is there

**Comment by tinchodias** [comment]
Fixed format in https://github.com/pharo-graphics/Alexandrie/commit/e9e1d949067da18231eb7951ff93d634c4bec952
