### ISSUE TITLE
Can we merge fenster package into Bloc?

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#182]
There is no other user of these four classes

**Comment by tinchodias** [comment]
The code is already in this repo, but it's not renamed, do you mean that?

https://github.com/pharo-graphics/Bloc/tree/master/src/Fenster
https://github.com/pharo-graphics/Bloc/tree/master/src/Fenster-Tests

**Comment by Ducasse** [comment]
Ok I did not notice that it was in the same repo. 
Now we could rename it bloc-something.

**Comment by astares** [comment]
Crazy to read the class names due to the project name and mixed language: because "Fenster" is "Window" in german. So "FensterPosition" is basically "WindowPosition" ...

**Comment by tesonep** [comment]
I think we should rename them to Window so it is clear. Thanks for the hint @astares

**Comment by tinchodias** [comment]
I renamed to Bloc-Display, I hope you agree! Using the word window was weird as it's not used in Bloc (a BlSpace is a window).

**Comment by tinchodias** [comment]
It could be also Bloc-ScaleFactor, or Bloc-Space-ScaleFactor, because these classes are about the scale factor, that makes that in retina (HiDPI), 200@200 size means 400@400.

**Comment by Ducasse** [comment]
Ok perfect. This is good to remove this dependency.
