### ISSUE TITLE
[BUG+FIX] - error on BlElement >> isLastChild

### ISSUE THREAD

**Issue by Nyan11** [pharo-graphics/Bloc#205]
Hello,

# Description

I found a bug while i was writting unit tests on a project.

The method `BlElement >> isLastChild` doesn't return the correct result. There is also a mistake in the comment of the method.

Is this method any useful ?

severity: not important.

# Reproduction

code to reproduce:

```st
| origin e1 e2 e3 |
origin := BlElement new.
e1 := BlElement new.
e2 := BlElement new.
e3 := BlElement new.

origin addChildren: { 
	e1.
	e2.
	e3 }.

{
(origin childAt: 1) isLastChild.
(origin childAt: 2) isLastChild.
(origin childAt: 3) isLastChild.
}
```

current result:

```
{ false . false . false }
```

expected result:

```
{ false . false . true}
```

# Possible fix

In the method `BlElement >> isLastChild`:

```st
isLastChild
	"return true if the receiver is the last child of its parent"
	self hasParent ifFalse: [ ^ self error: 'Must have a parent' ].
	^ (self parent childIndexOf: self) = self parent children size
```

# Other

pharo image : Pharo-11.0.0+build.346.sha.b6ce4527b4f4881d6c6b4f968f1d1348b783b7a2 (64 Bit)
bloc version  : [4d71a7e] - 2023-01-16 12:43

**Comment by labordep** [comment]
@tinchodias is this normal ?

**Comment by plantec** [comment]
good catch!

**Comment by plantec** [comment]
can you just commit push your fixe ?

**Comment by tinchodias** [comment]
I just created a PR in the github web (edit file + create PR button), but a test would be great. Maybe @Nyan11 wants to do it? ;) or review my PR as it is

**Comment by Nyan11** [comment]
Hello,

yes i can write tests if you want.

I will update this issue when i'm finished

**Comment by tinchodias** [comment]
Great, thanks

**Comment by tinchodias** [comment]
This was fixed, AFAIR, so I close it. Thanks again.
