### ISSUE TITLE
[BUG ?] - BlElement >> exportAsForm doesn't export the exact same shape

### ISSUE THREAD

**Issue by Nyan11** [pharo-graphics/Bloc#214]
Hello,

# Description

I was playing with the method `exportAsForm` ans i discover that it doesn't display the same shape as the one displayed inside a space.

severity: low

# Reproduction

### Example 1 - without bug

code to reproduce:

```st
parent := BlElement new
	background: Color green;
	size: 100 asPoint;
	id: #parent;
	yourself.

son1 := BlElement new 
	background: Color blue;
	size: 10 asPoint;
	id: #son;
	relocate: 10 @ 10;
	yourself.

son2 := BlElement new 
	background: Color red;
	size: 10 asPoint;
	id: #son;
	relocate: 101 @ 101;
	yourself.

parent addChild: son1.
parent addChild: son2.

parent openInNewSpace.

form := parent exportAsForm inspect.
```

in this example, an element `#father` as 2 sons.

+ The first son in blue is inside the bounds of its father. It should display in the space and in the form.
+ The second son in red is outside the bounds of its father. It shouldn't display in the space and in the form.

![image](https://user-images.githubusercontent.com/34318678/220579960-9b22a879-4cca-4c3a-a7b3-ac8218616ecb.png)

### Example 2 - with the bug

code to reproduce:

```st
parent := BlElement new
	background: Color green;
	size: 100 asPoint;
	id: #parent;
	clipChildren: false;
	yourself.

son1 := BlElement new 
	background: Color blue;
	size: 10 asPoint;
	id: #son;
	relocate: 10 @ 10;
	yourself.

son2 := BlElement new 
	background: Color red;
	size: 10 asPoint;
	id: #son;
	relocate: 101 @ 101;
	yourself.

parent addChild: son1.
parent addChild: son2.

parent openInNewSpace.

form := parent exportAsForm inspect.
```

This example is the same as `Example 1` except the `#father` is not clipping it's children. So we should expect to see both of the children in the space and in the form.

![image](https://user-images.githubusercontent.com/34318678/220583849-a1645964-539f-4f64-9b51-872b0896906c.png)

We can see the red and blue sons in the space but only the blue son in exportAsForm.

### Example 3 - with the bug

code to reproduce:

```st
parent := BlElement new
	background: Color transparent;
	size: 100 asPoint;
	id: #parent;
	yourself.

son1 := BlElement new 
	background: Color blue;
	size: 10 asPoint;
	id: #son;
	relocate: 10 @ 10;
	yourself.

son2 := BlElement new 
	background: Color red;
	size: 10 asPoint;
	id: #son;
	relocate: 101 @ 101;
	yourself.

parent addChild: son1.
parent addChild: son2.

parent openInNewSpace.

form := parent exportAsForm inspect.
```

This example is the same as `Example 1` except the `#father` is now transparent. For some reasons, when an element is transparent it doesn't clip it's children. So we should expect to see both of the children in the space and in the form.

![image](https://user-images.githubusercontent.com/34318678/220580850-f443594b-ba1a-44c6-81ef-fe01a3fdaaca.png)

We can see the red and blue sons in the space but only the blue son in exportAsForm.

### expected results

The form should display all the visible shape (without a transparent background) that are shown in the space.

![image](https://user-images.githubusercontent.com/34318678/220586152-08ce1909-8c04-40b7-b282-3638f54d0315.png)

# Other

pharo image : Pharo-11.0.0+build.346.sha.b6ce4527b4f4881d6c6b4f968f1d1348b783b7a2 (64 Bit)
bloc version  : [0f50d36] - 2023-02-16 15:16
bloc host : SDL2
bloc renderer : Alexandrie

**Comment by Nyan11** [comment]
For the `Example 3` see https://github.com/pharo-graphics/Bloc/issues/215 for why the elmeent isnot clipping its children

**Comment by tinchodias** [comment]
This could be fixed by a change in `BlExporter>>#computeBounds`, maybe sending `withAllChildrenBreadthFirstDo:` to `anElement`  and `merge:` the bounds of each child.

Or by putting it clear that export works like now, but providing a manual way to set the canvas size to draw it. Even a margin could be useful, no?
