### ISSUE TITLE
[Bug] - clipChildren doesn't work with transparent background

### ISSUE THREAD

**Issue by Nyan11** [pharo-graphics/Bloc#215]
Hello,

# Description

You can't clip when an element as a transparent background.

severity: high

# Reproduction

### Example 1 - without bug

code to reproduce:

```st
parent := BlElement new
	background: Color green;
	size: 100 asPoint;
	id: #parent;
	clipChildren: true;
	yourself.

son1 := BlElement new 
	background: Color blue;
	size: 10 asPoint;
	id: #son;
	relocate: 10 @ 10;
	yourself.

son2 := BlElement new 
	background: Color red;
	size: 10 asPoint;
	id: #son;
	relocate: 101 @ 101;
	yourself.

parent addChild: son1.
parent addChild: son2.

parent openInNewSpace.
```

in this example, an element #father as 2 sons.

+ The first son in blue is inside the bounds of its father. It should display in the space and in the form.
+ The second son in red is outside the bounds of its father. It shouldn't display in the space and in the form.

![image](https://user-images.githubusercontent.com/34318678/220587838-5eb197d1-1b6c-4880-a1ce-dc6c411c48f6.png)

### Example 2 - with the bug

code to reproduce:

```st
parent := BlElement new
	background: Color transparent;
	size: 100 asPoint;
	id: #parent;
	clipChildren: true;
	yourself.

son1 := BlElement new 
	background: Color blue;
	size: 10 asPoint;
	id: #son;
	relocate: 10 @ 10;
	yourself.

son2 := BlElement new 
	background: Color red;
	size: 10 asPoint;
	id: #son;
	relocate: 101 @ 101;
	yourself.

parent addChild: son1.
parent addChild: son2.

parent openInNewSpace.
```

![image](https://user-images.githubusercontent.com/34318678/220588080-ee4d46bd-f0c4-491f-a301-96e246b04097.png)

The red sons should not display.

### expected results

If we decide to clip the children, all children out of bounds shoud not render even if the background is transparent.

![image](https://user-images.githubusercontent.com/34318678/220589228-73ff303a-8a5e-49ce-855b-6e91525a06b1.png)

# Other

pharo image : Pharo-11.0.0+build.346.sha.b6ce4527b4f4881d6c6b4f968f1d1348b783b7a2 (64 Bit)

bloc version : [https://github.com/pharo-graphics/Bloc/commit/0f50d3633e1dcea806aa20c171e984f385c06bbd] - 2023-02-16 15:16

bloc host : SDL2

bloc renderer : Alexandrie

**Comment by Nyan11** [comment]
The `#father` as a `BlPaintBackground`.

+ opacity : nil
+ paint : BlColorPaint
  + color : `Color transparent`

**Comment by Nyan11** [comment]
The bug is also present with:

```st
parent := BlElement new
	background: BlBackground transparent;
	size: 100 asPoint;
	id: #parent;
	clipChildren: true;
	yourself.

son1 := BlElement new 
	background: Color blue;
	size: 10 asPoint;
	id: #son;
	relocate: 10 @ 10;
	yourself.

son2 := BlElement new 
	background: Color red;
	size: 10 asPoint;
	id: #son;
	relocate: 101 @ 101;
	yourself.

parent addChild: son1.
parent addChild: son2.

parent openInNewSpace.
```

**Comment by tinchodias** [comment]
I prepare a fix! thanks for reporting
