### ISSUE TITLE
BlElement id not return a Symbol (but a BlElementNamed)

### ISSUE THREAD

**Issue by labordep** [pharo-graphics/Bloc#219]
Do this code : 
`
ble := BlElement new.
ble id: #hello.
`
When inspect `ble id` this is not `#hello` but a `BlElementNamedId`. This should be the setted Symbol.

**Comment by tinchodias** [comment]
I guess this comes from the decision to wrap ids in object, deriving on this class hierarchy:
<img width="149" alt="Screenshot 2023-04-03 at 18 26 56" src="https://user-images.githubusercontent.com/3044265/229640534-245f7922-b3b3-4a82-88aa-253412870b30.png">

No idea if it was really required.

**Comment by tinchodias** [comment]
Bah, anyway the `id` method could unwrap the symbol before answering it, no?

**Comment by labordep** [comment]
yes :) it should be a good solution : that is important is to have coherents In/Out.
Concerning inside, I'm asking me about use cases and necessity to have a `ElementId` object...

**Comment by plantec** [comment]
well, I do not see any use of BlElementId subclasses and an id is just a data.
It can be any object in fact. So I would remove BlElementId hierarchy.

**Comment by tinchodias** [comment]
@labordep should we close this issue?

I see this is true now:
```smalltalk
ble := BlElement new. ble id: #hello.
ble id == #hello. "true"
```

**Comment by labordep** [comment]
@tinchodias yes this is ok with https://github.com/pharo-graphics/Bloc/pull/297 !

**Comment by tinchodias** [comment]
Great! thanks
