### ISSUE TITLE
Remove duplicated BlElement API in BlSpace?

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Bloc#229]
`BlSpace` exposes part of the API of `BlElement` by resending the message to its root.
The one that I most use is `addChild:`, which is handy, but sometimes want to use some element's method and realize is is not exposed in space.

Concretely, a space has around 25 methods like this:
```
addChild: anElement
	"Add a given element as a direct child to the space root"
	
	self root addChild: anElement
```

And it may be good idea to remove them and just access the space's root and use the full element API.

**Comment by tinchodias** [comment]
I forgot to say above that the API I'm talking about is only convenience/handy to write small examples in the Workspace. I don't see that a space should be polymorphic with element.

Also, the space has enough own responsibilities: IMO, the space-specific API would be easier to browse and discover after this clean up.

**Comment by plantec** [comment]
yes!!!!
I was also thinking that they should be removed

**Comment by tinchodias** [comment]
I wonder what's the rewriting rule to place in the deprecation in this case:
```smalltalk
BlSpace new
   addChild: anElement;
   show
```
An option is:
```smalltalk
| space |
space := BlSpace new.
space root addChild: anElement.
space show
```
or...
```smalltalk
BlSpace new
   in: [ :space | space root addChild: anElement ];
   show
```
But in both cases it requires the introduction of a variable name, and not sure if the automatic deprecation migration allows that.

**Comment by tinchodias** [comment]
I just looked for senders of addChild: in packages including "Bloc" and there are 328. Didn't check at Toplo and others. But in the Bloc packages I don't see so many occurrences that should be rewritten. So, may be not use automatic migration rule.

**Comment by tinchodias** [comment]
Let's close as @plantec already did it
