### ISSUE TITLE
Layout - Cassowary?

### ISSUE THREAD

**Issue by tblanchard** [pharo-graphics/Bloc#25]
I've been doing a lot of iOS development for awhile and Apple's "AutoLayout" turns out to be a port of the Cassowary constraints based layout model.  There is a version for Morphic that can be found at:

http://map.squeak.org/package/b2433b1a-2c28-432e-a091-1203eb92183c

For iOS development I've been using the library PureLayout and find it both intuitive and effective.  I don't yet understand Bloc's layout model, but I have become comfortable with Cassowary constraints based layout via "AutoLayout" and enjoy using it.  

I would be interested in your thoughts on this topic.

tblanchard@mac.com

**Comment by syrel** [comment]
Hello Todd,

Indeed, Cassowary layout looks very useful :) In fact, it is on my todo list for Bloc.
We will see how to port it.

Thanks for the link!
Alex

**Comment by StephanEggermont** [comment]
The license for that package is problematic. It is claimed to be LGPL. I looked at it, and the relevant parts for us are the parts that are originally public domain. The main reason to go for LGPL seems to be that other language Cassowary implementations were done as LGPL. The other language implementations  are moving towards  an Apache style license, which is not so practical for us either. We can just extract the original public domain parts and use those

**Comment by tblanchard** [comment]
That port is indeed LGPL.  However the original Smalltalk implementation is here: http://cassowary.cvs.sourceforge.net/viewvc/cassowary/cassowary/smalltalk/ (I just found it) and the Readme puts this code in the public domain.

**Comment by ThierryGoubier** [comment]
https://github.com/ThierryGoubier/Cassowary

Did that 3 years ago out of the public domain code. All tests were green on Pharo 3 or 4.
