### ISSUE TITLE
[FT] - BlCompositeEffect missing Alexendrie drawing method

### ISSUE THREAD

**Issue by Nyan11** [pharo-graphics/Bloc#253]
Hello,

# Description

BlCompositeEffect is missing aeDrawAbove: aBlElement on: anAeCanvas and aeDrawBelow: aBlElement on: anAeCanvas methods

severity: very low (but i already di it)

# Reproduction

```st
element := BlElement new background: Color gray; yourself.

shadow1 := BlGaussianShadowEffect color: Color red width: 20 offset: 10 @ 20.
shadow2 := BlGaussianShadowEffect color: Color green width: 20 offset: -10 @ 20.
shadow3 := BlGaussianShadowEffect color: Color blue width: 20 offset: 20 @ -10.
composite := BlCompositeEffect effects: { shadow1 . shadow2 . shadow3 }.

element effect: composite
element openInNewSpace.
```

current result:

![image](https://github.com/pharo-graphics/Bloc/assets/34318678/0b6033bf-1ddb-4ab7-bc15-9915a6a86d30)

expected result:

![image](https://github.com/pharo-graphics/Bloc/assets/34318678/8ed8ad57-b228-42e6-910d-5c914578cbf0)

# Possible fix
 Implement both methods (i did it, i prepare the pull request).

**Comment by tinchodias** [comment]
Nice example! 
We should add a render test, in BARenderTest + a PNG (in fact, the example must be added in BlSpaceFixture).
AFAIU, I am the only one that added tests there and think it's not trivial without a good guide... I can take care of adding this test unless you want to do it and I can explain how to.
(I add it to my to-do for the moment)

**Comment by tinchodias** [comment]
Nice, it works.

<img width="224" alt="Screenshot 2023-05-23 at 10 53 52" src="https://github.com/pharo-graphics/Bloc/assets/3044265/04daa16d-9104-4bab-a9a7-c9a33e65f2c9">


Only added position:
```
element := BlElement new
	background: Color gray;
	position: 100 @ 100;
	yourself.

shadow1 := BlGaussianShadowEffect color: Color red width: 20 offset: 10 @ 20.
shadow2 := BlGaussianShadowEffect color: Color green width: 20 offset: -10 @ 20.
shadow3 := BlGaussianShadowEffect color: Color blue width: 20 offset: 20 @ -10.
composite := BlCompositeEffect effects: { shadow1 . shadow2 . shadow3 }.

element effect: composite.
element openInNewSpace.
```

So, we close the issue.

**Comment by tinchodias** [comment]
Hi @Nyan11 I adapted your example as a test in: https://github.com/pharo-graphics/Bloc/commit/39cb92edfdc9ba687155b872e98f8144be3ad5f6

Thanks!
