### ISSUE TITLE
SDL crashes when resizing my space 

### ISSUE THREAD

**Issue by Enzo-Demeulenaere** [pharo-graphics/Bloc#256]
I have a space containing a squareElement (using a squareLayout) and I want my space to resize itself so it keeps a square shape but when I'm resizing my window/space, at some point, SDL crashes with this Error 

<img width="1621" alt="Capture d’écran 2023-05-22 à 14 26 19" src="https://github.com/pharo-graphics/Bloc/assets/121249182/d91b6004-fb50-4963-a8cb-7226e0674299"> 

and my window now looks like this : 

<img width="1294" alt="Capture d’écran 2023-05-22 à 14 28 06" src="https://github.com/pharo-graphics/Bloc/assets/121249182/b0c69c93-8817-409b-83c7-2e3379f2bdbb">

so here's a snippet : 

```
space := BlSpace new.

squareElement := BlElement new
	background: Color lightBlue;
	layout:
		((BlSquaredLayout on:
			BlLinearLayout horizontal alignCenter)
				beTight;
				yourself);
	constraintsDo: [ :c |
		c horizontal matchParent.
		c vertical matchParent ];
	addEventHandlerOn: BlElementExtentChangedEvent
		do: [ :evt | space extent: evt target extent ].

space addChild: squareElement.
space pulse.
space show.
^ space
```

> Note : This bug only appears when upscaling my window, playing with smaller sizes doesn't do anything

You can reproduce the bug by just upscaling the window, a few tries might be required 

My settings are as such : 

<img width="507" alt="Capture d’écran 2023-05-22 à 14 33 10" src="https://github.com/pharo-graphics/Bloc/assets/121249182/dcbdd52f-b2fe-4907-b7c6-480b59908009">

**Comment by tinchodias** [comment]
I reproduce it here. Will debug a bit.

**Comment by tinchodias** [comment]
In my opinion, your scenario is a bit weird because the window extent can be determined in both ways:
- The user by **dragging** the border with the cursor
- The element inside, triggering a change in space **immediately** after an element resize
... and you may accept doing it in other way. Okay, you can convince us this is required and debug more, but maybe you take one of these alternative solutions:

1) Set `space resizable: false` so the window size is only determined by the element (the user can't drag the border):
```
space := BlSpace new.

squareElement := BlElement new
	background: Color lightBlue;
	layout:
		((BlSquaredLayout on:
			BlLinearLayout horizontal alignCenter)
				beTight;
				yourself);
	constraintsDo: [ :c |
		c horizontal matchParent.
		c vertical matchParent ];
	addEventHandlerOn: BlElementExtentChangedEvent
		do: [ :evt | space extent: evt target extent ].

space addChild: squareElement.
space resizable: false.
space show
```


2) Do the window resize only after some idle milliseconds passed.
One way is using this OmDeferrer, but maybe just a fork with a small wait is enough):
```
space := BlSpace new.

spaceFitToContentsDeferrer := OmDeferrer
	send: #value
	to: [ space extent: squareElement extent ]
	after: 250 milliSeconds.

squareElement := BlElement new
	background: Color blue;
	layout:
		((BlSquaredLayout on:
			BlLinearLayout horizontal alignCenter)
				beTight;
				yourself);
	constraintsDo: [ :c |
		c horizontal matchParent.
		c vertical matchParent ];
	addEventHandlerOn: BlElementExtentChangedEvent
		do: [ :evt | spaceFitToContentsDeferrer schedule ].

space addChild: squareElement.
space show.
```

**Comment by tinchodias** [comment]
What do you think, @Enzo-Demeulenaere ? did you find a solution finally?

**Comment by tinchodias** [comment]
Please re-open if needed
