### ISSUE TITLE
Loading warning on P12

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Bloc#258]
On Pharo 12, not in P11:
```
Warning: Package Bloc-Text-Font depends on the following classes:
  RBMultiKeywordLiteralToken
You must resolve these dependencies before you will be able to load these definitions: 
  RBMultiKeywordLiteralToken>>#acceptVisitor:
```

<img width="872" alt="Screenshot 2023-05-23 at 11 06 45" src="https://github.com/pharo-graphics/Bloc/assets/3044265/1c89960e-5b3c-448d-bc78-17fc4c65d3de">

**Comment by tinchodias** [comment]
There are still other extensions on RB tokens:

<img width="216" alt="Screenshot 2023-05-23 at 11 19 33" src="https://github.com/pharo-graphics/Bloc/assets/3044265/0ebf52ef-ae79-4b59-8a76-4b14bf4b6cd5">

They interact with this styler:
```smalltalk
BlTextStyler subclass: #BlRBScannerTextStyler
	instanceVariableNames: 'parentheseLevel bracketLevel isForWorkspace workspace fontName classOrMetaClass'
	classVariableNames: ''
	package: 'Bloc-Text-Text-Styler'
```

And don't see users on a Bloc nor Toplo+Album image.

@plantec do you know?

**Comment by plantec** [comment]
we can remove BlRBScannerTextStyler

**Comment by plantec** [comment]
I've added it as another example of styler, but it not really useful

**Comment by plantec** [comment]
normally it's ok now

**Comment by tinchodias** [comment]
thanks!
