### ISSUE TITLE
[BUG] - External allocation failed with empty size elements

### ISSUE THREAD

**Issue by Nyan11** [pharo-graphics/Bloc#264]
Hello,

# Description

I discorver that element who have a height or a width of 0 cannot be previewed in the inspector. This doesn't affect the display in a space.

severity: very low

# Reproduction

code to reproduce:

```st
element := (BlElement new
	size: 0 @ 100;
	border: (BlBorder paint: Color blue width: 20);
	beOutskirtsOutside;
	yourself).
element aeAsForm. "Method used to display the preview in the inspector."
element openInNewSpace "When open in a new space everithing works fine."
```

current result:

![image](https://github.com/pharo-graphics/Bloc/assets/34318678/70b795a7-ba36-45cd-9094-d5efb7cdf2e0)

When executed, i get the same error as using `aeAsForm`.
It is generated by `FFIExternalArray` on the method: `initializeType: aType size: aNumber handleProducer: aBlock`.

expected result (as it is in a space):

![image](https://github.com/pharo-graphics/Bloc/assets/34318678/1ab8a5f2-d582-47d9-aaf3-e8822e27375b)

# Other

Bloc version: 0ad3d15 2023-05-30 01:15

**Comment by tinchodias** [comment]
Actually the Form returned should include the border and then be width>0.
But I'll also do handle the 0 width case. Thanks for the report!

**Comment by tinchodias** [comment]
This is now the result. Do you agree it is good to export the whole element, or did you need to ignore outskirt borders?

<img width="295" alt="Screenshot 2023-07-17 at 19 19 14" src="https://github.com/pharo-graphics/Bloc/assets/3044265/a7cbf933-0ed4-42c9-9281-2af234e66e12">

**Comment by tinchodias** [comment]
Fixed by https://github.com/pharo-graphics/Alexandrie/commit/94605017e293c81b3d46c46f8696c5f2e07d8286

**Comment by tinchodias** [comment]
(Fixed by those 2 commits)
