### ISSUE TITLE
Multiple reference to OBl classes

### ISSUE THREAD

**Issue by Nyan11** [pharo-graphics/Bloc#271]
Hello,

I just saw multiple unknow classes in Bloc.

```txt
NewUndeclaredWarning: BlElement>>inSpace (OBlSpace is Undeclared)
NewUndeclaredWarning: BlLayoutErrorHandler>>processError: (OBlInfiniteElement is Undeclared)
NewUndeclaredWarning: Bloc class>>preferencesOn: (OBlInfiniteMouseScrollListener is Undeclared)
```

I found them while i was trying to fix a bug on the CI of my project. (The CI of Bloc also show this 3 lines, but it doesn't stop it).

I also suspect `NewUndeclaredWarning: Bloc class>>preferencesOn: (OBlInfiniteMouseScrollListener is Undeclared)` to break the system settings of Pharo. It's a `<systemsettings>` method.

### informations

Pharo 11.0.0 Build information: Pharo-11.0.0+build.692.sha.0c234f2f5a92b237dd22ef9429506e92e586c494 (64 Bit)
Bloc version : 69c0e7c 2023-07-03 20:32

**Comment by tinchodias** [comment]
Do you know Alain @plantec ?

**Comment by plantec** [comment]
my fault certainly
i will have a look

**Comment by tinchodias** [comment]
@Nyan11  please reopen if required. Thanks @plantec !
