### ISSUE TITLE
[Feature] - Border with gradients

### ISSUE THREAD

**Issue by Nyan11** [pharo-graphics/Bloc#273]
Hello,

I was trying to draw borders with a gradient but apparently it's not possible. Also the border as a `paint:` value but can only `Color` object and not take `BlPaint` object.

## Example 1 : With a Color

```st
border := BlBorderBuilder new width: 5; paint: Color black; build.
e := BlElement new position: 50 @ 50 ; border: border; yourself.
e openInNewSpace.
```

![image](https://github.com/pharo-graphics/Bloc/assets/34318678/1e97d879-57bc-47aa-b82d-f209cb6bc6b8)

## Example 2 : With a simple BlPaint

```st
paint := BlLinearGradientPaint vertical from: Color blue to: Color red; yourself.

border := BlBorderBuilder new width: 5; paint: paint; build.
e := BlElement new position: 50 @ 50 ; border: border; yourself.
e openInNewSpace.
```

It show an error. `DNU for: BlLinearGradientPaint >> #aeApplyTo:`

**Comment by tinchodias** [comment]
I'm on a fix, thanks for the report... I actually never implemented it in the Alexandrie canvas.

**Comment by tinchodias** [comment]
@Nyan11 now working like this:

<img width="512" alt="Screenshot 2023-07-17 at 23 44 57" src="https://github.com/pharo-graphics/Bloc/assets/3044265/f5b7690e-8539-462a-870e-de01e1bbaadb">

```smalltalk
	extent := 200 @ 300.
	borderWidth := extent x // 3.

	aLinearGradient := BlLinearGradientPaint new
			start: 0@0;
			end: 0 @ extent y;
			stops: {
				0.0 -> Color blue.
				0.3 -> Color yellow.
				1.0 -> Color transparent };
			yourself.
	a := BlElement new
		beOutskirtsCentered;
		position: extent // 5;
		size: extent;
		background: (Color orange alpha: 0.75);
		border: (BlBorder paint: aLinearGradient width: borderWidth);
		yourself.

	aRadialGradient := BlRadialGradientPaint new
			center: extent;
			radius: extent x;
			stops: {
				0.0 -> Color blue.
				0.3 -> Color yellow.
				1.0 -> Color transparent };
			yourself.
	b := BlElement new
		beOutskirtsCentered;
		position: extent * 0.75;
		size: extent;
		background: (Color green alpha: 0.75);
		border: (BlBorder paint: aRadialGradient width: borderWidth);
		yourself.

	aSpace := BlSpace new.
	aSpace root addChild: a; addChild: b.
	aSpace extent: extent * 2; show.
```

**IMPORTANT NOTE:** the gradients for borders do not do `matchExtent:`... probably they should, for consistency with when they are used as backgrounds.
