### ISSUE TITLE
Fix BlDevScripterExamples>>clickCheck

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Bloc#287]
One of the tests failing in CI #282

The test is:
```
clickCheck
<gtExample>
    | anElement aScript |
    anElement := BlDevElementExamples new containerWithRectangle.
    aScript := self basicScripter element: anElement.
    aScript click onChildAt: 1.
    aScript check click onChildAt: 1.
    aScript play.
    ^ aScript
```

The expression `aScript click onChildAt: 1.` makes an instance of `BlDevScripterCheckFiredEventsStep`, which asserts that a pending event in the space is instance of `BlClickEvent`:

```
assertEventClass: anEventClass withTarget: aBlElement on: aScripter 
	| theInterestingEvents |
	theInterestingEvents := aScripter events select: [ :eachEvent | 
		eachEvent class = anEventClass and: [ eachEvent target = aBlElement ] ].
	self assert: theInterestingEvents notEmpty.
```

However, `BlClickEvent` is now the head of a hierarchy:
`BlClickEvent subclasses ">> {BlMiddleClickEvent. BlPrimaryClickEvent. BlSecondaryClickEvent}"`

I think, as a solution, that the assert on `BlDevScripterCheckFiredEventsStep` can use a isKindOf: instead os class equality.

**Comment by plantec** [comment]
ah, yes of course. thanks
