### ISSUE TITLE
We should be able to add/remove child at index

### ISSUE THREAD

**Issue by syrel** [pharo-graphics/Bloc#3]
introduce in BlElement
  - `addChild: anElement before: anotherElement`
  - `addChild: anElement after: anotherElement`
  - `addChild: anElement at: anIndex`
  - `removeChildAt: anIndex`

**Comment by GlennCavarle** [comment]
Maybe, what is your need which would imply the ability to play with index and anchor elements?

**Comment by syrel** [comment]
Could you show an example of how to add an element in the middle of the list? :slightly_smiling_face: 
The only two methods we have now are `addChild:` and `addChildFirst:`. Unfortunately I don't see any ways to add an element before or after specific element

**Comment by syrel** [comment]
JavaFX:
- parent.getChildren().add(int index, E element)

iOS:
– insertSubview:aboveSubview:
– insertSubview:belowSubview:
– insertSubview:atIndex:

Android:
- public void addView(View child, int index) 

jQuery:
- .insertAfter()
- .insertBefore()

Bloc:
 - no

**Comment by GlennCavarle** [comment]
I see the interest, i just wanted to know if you have an actual need for.
You removed the "enhancement" label so, it lets me think that it should be done quickly.

**Comment by syrel** [comment]
I didn't want to add any label at all :slightly_smiling_face:
Could find a way to to remove label history.

Yes, I need it asap. Will add tomorrow (today, actually, it's 1:37am already :D)

**Comment by syrel** [comment]
done
