### ISSUE TITLE
Move Bloc-Theme to Toplo

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Bloc#309]
I see senders of `theme`in Toplo, and there is a class for notebook, for example. 
This package's contents look very oriented to Toplo. Am I wrong?

@labordep @plantec

**Comment by plantec** [comment]
Hello,
which classes ?
which methods ?
thanks

**Comment by tinchodias** [comment]
Hi
The package looks like this:
<img width="419" alt="Screenshot 2023-09-08 at 10 04 49" src="https://github.com/pharo-graphics/Bloc/assets/3044265/ca87b9c4-b306-446a-b817-90b50186a17b">

And it adds this extension to element:
<img width="650" alt="Screenshot 2023-09-08 at 10 06 55" src="https://github.com/pharo-graphics/Bloc/assets/3044265/4772d137-d8df-4349-a703-3195cef42709">

And only guess these are the senders:
<img width="821" alt="Screenshot 2023-09-08 at 10 09 03" src="https://github.com/pharo-graphics/Bloc/assets/3044265/319a7f78-c4c6-46ac-ac97-c1efae0d841c">

**Comment by plantec** [comment]
ah ok.
all these classes a deprecated.
I will have a look and cleanup

**Comment by tinchodias** [comment]
Probably to be closed

**Comment by plantec** [comment]
not really, these classes will be removed.
It is still to be done :)

**Comment by jecisc** [comment]
Those classes are deprecated and do not seesm to be used anymore in Bloc. Should we close?

**Comment by plantec** [comment]
ok

**Comment by tinchodias** [comment]
I'll propose to remove this, it's annoying to have it undeclared:

<img width="648" alt="Screenshot 2024-03-04 at 23 23 23" src="https://github.com/pharo-graphics/Bloc/assets/3044265/250959a4-14e5-4e95-8a0c-d7175b06bb2b">
