### ISSUE TITLE
Regression due to the new version of SubscriptionRegistry>>#removeSubscriber: 

### ISSUE THREAD

**Issue by plantec** [pharo-graphics/Bloc#331]
DNU in BlHandlerAnnouncerRegistry>>#remove: 
(sent from BlElementEventDispatcher>>removeEventHandler:)

**Comment by tinchodias** [comment]
Ah! I saw it but was confused if it was something wrong I did locally. Do you know the cause of this error? Yesterday I was trying to find a fixed version of Toplo:master + Bloc:dev-1.0 and got this error.

**Comment by tinchodias** [comment]
For the record. Pablo explained it here:
https://discord.com/channels/223421264751099906/278558427796602882/1161996071665414194

-->

When there was an object with multiple announcements subscribed on it, the subscription was added many times as ephemerons, all waiting for the garbage collection of the receiver. If we leave them to be finalized by the ephemeron mechanism they were finalized one by one, taking a lot of GCs processes to remove them. This was specially a problem with the ChangeSet, as it can arrive to have thousands of subscriptiosn if they are not correclty cleaned. So now when we unsubscribe a given subscriber we remove all the weakSubscriptions and remove the associated ephemerons. https://github.com/pharo-project/pharo/pull/14951

**Comment by tinchodias** [comment]
v2.0.0-alpha has this problem in P11 and 12. Test with:

```
e := BlElement new.
handler := (BlEventHandler on: BlMouseMoveEvent do: [ :evt | e background: Color random ]).
e addEventHandler: handler .
e removeEventHandler: handler. 
```

**Comment by tinchodias** [comment]
There is no problem with removeEventHandler: now in v2.0.0
