### ISSUE TITLE
Repositioning rotated elements leaves artefacts

### ISSUE THREAD

**Issue by StephanEggermont** [pharo-graphics/Bloc#34]
If I create a BlElement with a coloured background that I rotate by 4 degrees and add an event handler allowing the dragging of that element over its space, it leaves artefacts, i.e. the area to redraw is not calculated correctly.

**Comment by syrel** [comment]
Fixed in: https://github.com/pharo-graphics/Bloc/commit/95d5e54db81e9883f009086392c56ba2d8d6f3ef
Added examples/tests `BlTransformationExamples`
