### ISSUE TITLE
Installation — MozTransformationBuilder error

### ISSUE THREAD

**Issue by darth-cheney** [pharo-graphics/Bloc#35]
Hi.

After downloading a fresh 6.0VM/Image, the Metacello installation in the README no longer works. I receive the following error during the installation:
  
```
This package depends on the following classes:
  MozTransformationBuilder
You must resolve these dependencies before you will be able to load these definitions: 
  MozTransformationBuilder>>#drawSurface:transformed:
  MozTransformationBuilder>>#primDrawSurface:matrix:


Select Proceed to continue, or close this window to cancel the operation.
```

**Comment by syrel** [comment]
Sorry, my fault.
You are installing #core version while Moz* classes are in #development. Bloc-Sparta package adds extension methods to not existing classes

**Comment by syrel** [comment]
Fixed
