### ISSUE TITLE
Fix SVG tree example

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Bloc#354]
Try: `BlSvgExamples new pathTree`

Actual:

<img width="472" alt="Screenshot 2023-11-15 at 16 08 01" src="https://github.com/pharo-graphics/Bloc/assets/3044265/f5786972-b724-4f6a-b6a9-5bdd3f846317">

Expected:

<img width="494" alt="Screenshot 2023-11-15 at 16 08 45" src="https://github.com/pharo-graphics/Bloc/assets/3044265/a27e8351-6c7f-40c5-89bb-1acf35043a7d">

**Comment by plantec** [comment]
I've made a pass on code generators. Now, they are in a separate class (ToMaterialDesignIconProviderGenerator and ToAntDesignIconProviderGenerator)
to use them:
ToMaterialDesignIconProviderGenerator generateIconProviderClassesFromSrcDirectotyNamed: 'material_design_src'.
ToAntDesignIconProviderGenerator  generateIconProviderClassesFromSrcDirectotyNamed: 'ant_svg'.
regarding generated code, now exactly the same code is generated for Ant and for Material design
especially,  metadata methods are prefixed with a _
_filled_loaded, filled_unloadable ...
the loaded/unloadable methods return a list of icon names (and not of generated method name)
the utility method #listElementWithAllIconsInProviderClass: is now in ToImportedIconProvider which is the superclass of all icon provider generated classes
It can be user the same manner for Ant and for Material design
example: 
(ToImportedIconProvider listElementWithAllIconsInProviderClass: ToMaterialDesignAlertIconProvider ) openInSpace.
(ToImportedIconProvider listElementWithAllIconsInProviderClass: ToMaterialDesignCommunicationIconProvider ) openInSpace.
(ToImportedIconProvider listElementWithAllIconsInProviderClass: ToMaterialDesignContentIconProvider ) openInSpace.
(ToImportedIconProvider listElementWithAllIconsInProviderClass: ToMaterialDesignMapsIconProvider ) openInSpace.
(ToImportedIconProvider listElementWithAllIconsInProviderClass: ToAntDesignIconProvider  ) openInSpace

**Comment by tinchodias** [comment]
@plantec to execute that Toplo code, should I load dev branch?

**Comment by tinchodias** [comment]
@plantec the bicycle should be fixed in Bloc:dev
Didn't search how to reproduce it, to check myself.

**Comment by plantec** [comment]
yes, dev should be used.
To generate the icon providers classes:
- for Ant design
- - ```ToAntDesignIconProviderGenerator  generateIconProviderClassesFromSrcDirectotyNamed: 'ant_svg'```
- - ant_svg should be the directory name where ant icons are stored
[ant-design-icons.zip](https://github.com/user-attachments/files/15526663/ant-design-icons.zip)

**Comment by plantec** [comment]
For Material design:
- remove all ToMaterialDesignIconProvider subclasses
- take care to keep ToMaterialDesignIconProvider
- then:
```ToMaterialDesignIconProviderGenerator generateIconProviderClassesFromSrcDirectotyNamed: 'material_design_src'.```
- 18 ToMaterialDesignIconProvider subclasses are generated, one class for each material design icon family (root direct subdirectory)
[material_design_src.zip](https://github.com/user-attachments/files/15526690/material_design_src.zip)
- Each ToMaterialDesignIconProvider class has the icon of one material_design_src direct subdirectory.
- You can view all the icons of a particular provider class as with the ant icons:
```
(ToImportedIconProvider listElementWithAllIconsInProviderClass: ToMaterialDesignAlertIconProvider ) openInSpace.
(ToImportedIconProvider listElementWithAllIconsInProviderClass: ToMaterialDesignCommunicationIconProvider ) openInSpace.
(ToImportedIconProvider listElementWithAllIconsInProviderClass: ToMaterialDesignContentIconProvider ) openInSpace.
(ToImportedIconProvider listElementWithAllIconsInProviderClass: ToMaterialDesignMapsIconProvider ) openInSpace.
```
- As for Ant, one can open a particular icon by its name:
```(ToIconSharpStyle iconNamed: '18mp' inProvider: ToMaterialDesignImageIconProvider) matchParent; openInSpace```.

**Comment by plantec** [comment]
I will update the code generator for material design because the structure of the GitHub repo or material design changed.
It will be simpler since the structure is the same as for Ant design, for the code generator should be the same

**Comment by tinchodias** [comment]
<img width="243" alt="Screenshot 2024-06-06 at 22 51 34" src="https://github.com/pharo-graphics/Bloc/assets/3044265/0ef9a819-1f51-4d18-a95e-ee9fb7f7b7b4">


Both work well now:
- The tree I reported in first comment
- The  icon described by Alain via chat `(ToIconFilledStyle iconNamed: 'accessible' inProvider: ToMaterialDesignIconProvider)  matchParent; openInSpace`
- Didn't check the rest of Material icons

**Comment by tinchodias** [comment]
@plantec I scrolled all icons and they seem to be good:
`(ToImportedIconProvider  listElementWithAllIconsInProviderClass: ToMaterialDesignIconProvider) openInSpace`
