### ISSUE TITLE
Spurious copy and initialization in compositeBackground

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#366]
```
BlCompositeBackground >> withAll: aCollectionOfBackgrounds
	"Return a composite background based on the collection of background pass as argument. 
	This collection of backgrounds must not be empty"

	backgrounds := aCollectionOfBackgrounds asArray copy
```

The copy is not necessary since asArray already creates one. 

It is unclear why it makes sense to initialize background to an empty array.

```
BlCompositeBackground >> initialize

	super initialize.
	backgrounds := Array new
```

**Comment by jecisc** [comment]
If the argument is already an array, then #asArray does not create a copy. But I'll propose a fix that copy only if the argument is an array

**Comment by Ducasse** [comment]
Yes this is what I saw. we cannot blinldy remove such asArray.

**Comment by jecisc** [comment]
I did a PR proposing to use #copy on array and #asArray on other collections
