### ISSUE TITLE
the difference between isFocused and focused is not clear enough from the selector point of view

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#369]
Especially since BlSpace defines it as follows

```
"window - properties"
focused

	^ focused
```

**Comment by tinchodias** [comment]
I'm replacing focused by isFocused (in BlSpace, BlElement and BlElementVisuals), and IT IS IGNORED! it is only a flag that has no effect

**Comment by plantec** [comment]
isFocused/focused work well in BlElement.
additionally, hasFocus return true if the receiver or one of it children is focused.
One have to send  #requestFocus to set the focus

**Comment by tinchodias** [comment]
I'm sorry, I wasn't precise: BlSpace>>focused: is not sent in the Morphic host. But SDL2 host updates the flag. 

The BlSpace>>focused: doesn't dispatch any event when it is changed, but it might be queried on execution... I didn't check that.

**Comment by tinchodias** [comment]
I've just discovered this method in `BlElement`, that confused me:
```
hasFocus
	"Return true if an element is focused or contains a focused element, false otherwise"

	^ self isFocused or: [
		self children anySatisfy: [ :anElement | anElement hasFocus ] ]
```

**Comment by tinchodias** [comment]
In https://github.com/pharo-graphics/Bloc/commit/c12428c917aa804514ce925690a125c259248c82 :
- Replace focused by isFocused in BlSpace, BlElement and BlElementVisuals.
- Deprecate the old name with a transform rule 

I think this closed this issue, but I will wait @Ducasse opinion

**Comment by Ducasse** [comment]
I do not have an opinion :)
I think that you are more precise than me on it.
