### ISSUE TITLE
Reduce number of broken tests in P12

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#377]
We should reduce the number of broken tests.

![Capture 2024-01-02 at 14 25 15](https://github.com/pharo-graphics/Bloc/assets/432549/b4083c0a-86a5-4298-9aca-3fcedf634b74)

**Comment by tinchodias** [comment]
Related to (or duplicated in): https://github.com/pharo-graphics/Bloc/issues/315

**Comment by tinchodias** [comment]
They are the same failures than in Pharo 11, after:
* https://github.com/pharo-graphics/Bloc/commit/a551511f9ea81aa8630cbeb9a95e0969dfaaa714
* https://github.com/pharo-graphics/Bloc/commit/51b81c76a196f0c3470c19df8dbc576d780d66f2
