### ISSUE TITLE
Running tests in P11

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#378]
Hi 

I got error due to BARenderer? And I do not get why I get far less tests in P11 than in P12.

![Capture 2024-01-02 at 14 39 40](https://github.com/pharo-graphics/Bloc/assets/432549/ff330ee5-46be-42e6-a939-8225ceca945b)

**Comment by tinchodias** [comment]
They use a Random instanced with a well known seed e.g. to choose colors, and the Random algorithm changed in P12

**Comment by tinchodias** [comment]
This was fixed by a551511f9ea81aa8630cbeb9a95e0969dfaaa714
