### ISSUE TITLE
BlMouseEventExamplesTest DNU

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#393]
```
pointToText: aPoint for: aTextElement
	aTextElement text: (aPoint asRopedText fontSize: 10; foreground: (aTextElement parent background paint color darker alpha: 1))
```
color was sent to nil

**Comment by Ducasse** [comment]
This test is not part of the log. So clearly not executed.

**Comment by tinchodias** [comment]
It works here. I placed a traceCr in pointToText:for: and a halt at the end of testParentWithClip in the same class:

<img width="818" alt="Screenshot 2024-01-19 at 16 37 59" src="https://github.com/pharo-graphics/Bloc/assets/3044265/8acbc48a-7b80-4917-8c8d-867d144b862f">

I'm pushing a clean up pass on BlMouseEventExamplesTest... I'm thinking that as demo they are good examples... I hope this doesn't produce merge conflicts with an @Enzo-Demeulenaere branch

**Comment by tinchodias** [comment]
> This test is not part of the log. So clearly not executed.

Maybe your point was that this was not executed by CI. In that case, I will remove the CI exclusion so all tests will run (and some fail).

**Comment by Ducasse** [comment]
I do not remember :( I should be more precise in my bug entry. But yes I would suggest that we enable step by step the tests.

**Comment by Ducasse** [comment]
What is super strange is that I'm sure it broke. 
now I will reload the latest version in P12 and check.
