### ISSUE TITLE
Styles are currently mocked. Do we remove them completely?

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Bloc#398]
BlElement>>styles returns nil, and the styles applying phase in the universe is not used. Toplo does not use them, right, @plantec ?

Senders of styles:
<img width="387" alt="Screenshot 2024-01-15 at 18 07 13" src="https://github.com/pharo-graphics/Bloc/assets/3044265/0570b595-e8c6-455a-9db9-0634994caf25">

and there are some more sender ramifications that are unused.

**Comment by tinchodias** [comment]
This would close https://github.com/pharo-graphics/Bloc/issues/132

**Comment by jecisc** [comment]
It was suggested to remove them from block and maybe keep them somewhere else for history.

If everyone agrees I can try to do it. (I like to do this kind of cleaning to get to know better new projects)

**Comment by plantec** [comment]
I would do it.
Thanks

**Comment by Ducasse** [comment]
Yes let us remove them!

**Comment by jecisc** [comment]
I opened a PR
