### ISSUE TITLE
Remove managed children

### ISSUE THREAD

**Issue by syrel** [pharo-graphics/Bloc#4]
Replace managed with more fine-grained properties (visible/hidden/gone/floating)

**Comment by GlennCavarle** [comment]
We already discussed about that, `managedChildren` is not really related to visibility.
`managedChildren` or more the notion of unmanaged children has to be replaced by a kind of "floating" option to mark the `element` as managed like in a frame layout. This behavior has to be implemented at the `BasicLayout` level to ensure that all layouts benefit from that.

**Comment by syrel** [comment]
> managedChildren is not really related to visibility.
Why? We found out that to answer the question "should child be managed by layout?" we also need to take visibility into account. If visibility is "gone" child must not be "managed": it should not be measured and should not participate in layout.
Floating is a bit different. Floating means that child is measured, but does not participate in layout and does not occupy space, for example within a list. It can be in the corner above all other elements.

Check discussion from 24th of October. Floating + fine-grained visibility option replace managed.

**Comment by syrel** [comment]
Also, I think there is a misunderstanding of what "managed children" means. In JavaFX there is a rule
**Rule: If you unmanage a node then you are solely responsible for its position and size (if its Resizable);  and don’t go there unless you know what you’re doing.**
So, unmanaged child will neither be measured nor layered out. This is not flexible enough for us.
Very often we want child to be measured (size is calculated automatically) but not layered out (we position it manually) :slightly_smiling_face:

**Comment by GlennCavarle** [comment]
Ok, my bad, we agree, `managedChildren` is not **only** related to visibility ;).
> Floating + fine-grained visibility option replace managed

**Comment by syrel** [comment]
Exactly :)

(I put most important things from our discussion in this thread to not lose them)

**Comment by girba** [comment]
`managedChildren` is now deprecated
