### ISSUE TITLE
Regression on BlCursor

### ISSUE THREAD

**Issue by ELePors** [pharo-graphics/Bloc#403]
Hi, 

All zones of my UI where i change the cursor is broken with latest version of Bloc.

exemple
```myBlSpace currentCursor: BlCursor crosshair```

BlCursor does not exist anymore... it was existent some month ago.
Thanks by advance.

Eric

**Comment by labordep** [comment]
Thanks @tinchodias!
We are enthusiastic about these developments, but please don't remove classes without a deprecation phase!

**Comment by tinchodias** [comment]
@ELePors @labordep now BlCursor exists again, with automatic rewriting deprecation that converts to "Cursor *". Do you think it's okay?

**Comment by tinchodias** [comment]
I tested BlCursor on my image with:

```
selectors := BlCursor class selectors.

c := Object subclass: #PruebaCursor.
selectors do: [ :each |
	c compile: ('{1} ^ BlCursor {1}' format: { each }) ].

selectors collect: [ :each |
	each -> (c new perform: each) ].
```
and seemed to work fine

**Comment by labordep** [comment]
Thanks!
I think this is ok if the two classes are equivalent.

**Comment by ELePors** [comment]
Thanks Martin, it's good !
