### ISSUE TITLE
Image freezing when try to debug events in SDL2 host

### ISSUE THREAD

**Issue by labordep** [pharo-graphics/Bloc#406]
Prerequisites: setup SDL as default host for Bloc:
![image](https://github.com/pharo-graphics/Bloc/assets/49183340/d6924028-9db8-4116-8e94-1006f36e7d39)

Example to reproduce:

```smalltalk
space := BlElement new openInSpace.
space title: 'test'.

"Install events listener"
space addEventHandler: (BlEventHandler
			 on: BlSpaceResizedEvent
			 do: [ :e | self haltOnce ])
```

Try to resize the opened window, the halt window is showed in the Pharo window by the image is freezing.
Same behavior when I'm trying to place breakpoints.

My config:
- Pharo-11.0.0+build.721
- VM 10.0.9
- Windows 11 Pro 64bits
But this problem was also reproduce in MacOs.

**Comment by tinchodias** [comment]
A concrete case for #396

**Comment by tinchodias** [comment]
Still reproduce it after #409

**Comment by tinchodias** [comment]
To fix this issue, I opened an issue in Pharo repository, with a proposal: https://github.com/pharo-project/pharo/issues/16076

**Comment by tinchodias** [comment]
This fix avoids the crash in the Bloc example (replacing Error by UnhandledException in `OSSDL2Driver>>#processEvent:`).

**Comment by tinchodias** [comment]
@labordep it's merged on Pharo 12. I will propose a backport to P11 now.

**Comment by labordep** [comment]
Thanks @tinchodias!

**Comment by tinchodias** [comment]
https://github.com/pharo-project/pharo/pull/16095 Merged 
So, @labordep this issue should be fixed in a Pharo 11 downloaded now.

**Comment by labordep** [comment]
Thanks @tinchodias!
