### ISSUE TITLE
Check unreferenced "BlSpace*Event"s 

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Bloc#408]
At least these:
- BlSpaceDragCancelEvent
- BlSpaceDragLiftEvent
- BlSpaceExposeEvent
- BlSpaceScaleFactorChangedEvent
- BlSpaceWakeUpEvent

**Comment by jecisc** [comment]
I was gonna open an issue asking if those were still needed or just something from the past since they are never raised :)

I would add BlSpaceMaximizedEvent and BlSpaceMinimizedEvent to the list?

**Comment by tinchodias** [comment]
Thanks. The fix of this issue may be not deleting the events but by contrary use them where they should be used.

For example, the superclass of `BlSpaceMaximizedEvent` is `BlSpaceResizedEvent` and it IS referenced. The method that should dispatch the maximize from the SDL2 host is `BlOSWindowEventHandler>>#visitWindowMaximizedEvent:`,  but it dispatches instead a `BlSpaceResizedEvent` 🤔
