### ISSUE TITLE
Is BLOverlay* needed

### ISSUE THREAD

**Issue by jecisc** [pharo-graphics/Bloc#414]
I see that we have `BlOverlayElement` and `BlOverlayListener` but those two classes are never referenced and have no test.

So I am wondering if they are still needed or if they should be removed?

**Comment by plantec** [comment]
It is useful and used in Toplo.
btw: maybe you should load toplo (main branch) to have an larger idea off users of Bloc classes.

EpMonitor disableDuring: [
  Author useAuthor: 'Load' during: [
    [ Metacello new baseline: 'Toplo'; repository: 'github://plantec/Toplo:main/src';
        onConflictUseIncoming;
        ignoreImage;
        load.
    ] on: MCMergeOrLoadWarning do: [ :warning | warning load ].
  ].
].

**Comment by jecisc** [comment]
I have Toplo in my image but there is no reference to both those classes

**Comment by plantec** [comment]
have a look at subclasses :)

**Comment by tinchodias** [comment]
So, we can either:
- Write new example in Bloc
- Move the 2 overlay classes to Toplo
- Just keep it like now

**Comment by tinchodias** [comment]
Sorry, there are examples in Bloc-Pac: https://github.com/pharo-graphics/bloc-pac/blob/dev-1.0/src/BlocPac-Overlay-Examples/BlOverlayElementExamples.class.st

I will bring them to Bloc
