### ISSUE TITLE
How to restart drawing/event process after closing debugger?

### ISSUE THREAD

**Issue by labordep** [pharo-graphics/Bloc#421]
Hi,

My problem is a concrete dynamic UI prototyping use-case.
We can edit UI on the fly (during running), for example using the debugger.
But sometimes, as human defaults, we make some mistakes. 
For example close the debugger window from a halt in the drawing stack (aeDrawOn:).

When close, my UI are not refreshing. I suppose the drawing thread is done.
I don't want to restart my UI, because I'm running a prototype with is context, so my question is: how to restart Bloc/SDL threads when they are done?  

An example in video, I have a window with buttons, I place a halt once in the drawind stack, I close the debugger (human mistake) and then the drawing thread is done.

https://github.com/pharo-graphics/Bloc/assets/49183340/bc3223da-df1b-46ca-9c75-bcdc1d2dee44

I suppose there is the same problem with SDL events stack @ELePors?

**Comment by tinchodias** [comment]
I reproduced programatically with:
```smalltalk
s := BlSpace new.
"s useMorphicHost."
s extent: 100 asPoint.
s root
	addEventHandlerOn: BlClickEvent
	do: [ :evt | evt target background: Color random ].
s show.

s root haltOnceOnCallTo: #aeDrawOn:.
```
and click on the space.


I usually do parts of:
```
BlOSWindowSDL2Host stop.
BlOSWindowSDL2Host universe tryToRunDeferredActions.
BlOSWindowSDL2Host start.
```

But I'm with the https://github.com/pharo-graphics/Bloc/pull/409 applied and this is fixed. I will merge it.

**Comment by tinchodias** [comment]
I merged the error handling PR #409... @labordep  please repeat the steps of your video, and should work as you expect.

**Comment by tinchodias** [comment]
@labordep do you agree we can close this issue?

**Comment by labordep** [comment]
@tinchodias yes all seems good with your example :) Thanks.
