### ISSUE TITLE
Bloc crashed on Save and Quit due to Moz2D shutdown services

### ISSUE THREAD

**Issue by sukoi26** [pharo-graphics/Bloc#44]
after download the package , i received segfault when i leave 

[crash.txt](https://github.com/pharo-graphics/Bloc/files/2254385/crash.txt)

**Comment by sukoi26** [comment]
i believe that is libmoz2d.so concern

**Comment by girba** [comment]
Thanks for the report. We are working on the subject, but it's a tricky problem.
