### ISSUE TITLE
Ghost windows are not closing + system cleanup feature

### ISSUE THREAD

**Issue by labordep** [pharo-graphics/Bloc#461]
Hi,

Related to #457, we have always ghost windows that are not closing correctly (SDL2).
This is not easy to reproduce at each time, I think we need to use a clean safety code.
Do you have the code below in a Bloc "system cleanup" feature ?

```smalltalk
BlOSWindowSDL2Host universe closeSpaces.
BlOSWindowSDL2Host
	stop;
	start.
BlMorphicWindowHost universe closeSpaces.
BlMorphicWindowHost
	stop;
	start 
```

This code, extracted from Toplo, is very useful for cleaning up ghost windows. If it exists, could we integrate this code when cleaning up the image via the system menu? 
![image](https://github.com/pharo-graphics/Bloc/assets/49183340/bfafe551-8280-4e56-a181-5f62f3154d9a)

Thanks :)

Config:
- Windows 10 Pro
- Pharo-11.0.0+build.725
- VM 10.1.0.0

**Comment by labordep** [comment]
After executing twice the test on #463 I have my ghost window.
After, I execute this code: 

```smalltalk
BlOSWindowSDL2Host universe closeSpaces.
BlOSWindowSDL2Host
	stop;
	start.
BlMorphicWindowHost universe closeSpaces.
BlMorphicWindowHost
	stop;
	start 
```

And after a `Do Image Cleanup` I got this error:
![image](https://github.com/pharo-graphics/Bloc/assets/49183340/ebc770bf-2676-4f93-92dc-6db1b6c74bd5)

**Comment by labordep** [comment]
@tinchodias I wrote a branch here https://github.com/pharo-graphics/Bloc/pull/464

**Comment by tinchodias** [comment]
The PRs are merged so I guess we can close this issue
