### ISSUE TITLE
First rules for Bloc

### ISSUE THREAD

**Issue by Enzo-Demeulenaere** [pharo-graphics/Bloc#474]
We started to write some rules to help defining BlElement
We attached the package code.

[Bloc-Rules.st.zip](https://github.com/pharo-graphics/Bloc/files/14570321/Bloc-Rules.st.zip)

**Comment by Enzo-Demeulenaere** [comment]
[Bloc-Rules2.st.zip](https://github.com/pharo-graphics/Bloc/files/14570519/Bloc-Rules2.st.zip)

**Comment by Enzo-Demeulenaere** [comment]
this above is a new rule that check if the method `forceLayout` is used in a method, this `forceLayout`method is commented as private and should not be called, the rule checks this

**Comment by tinchodias** [comment]
Fix was fixed by #481
