### ISSUE TITLE
Calling text: method to change text of a BlTextElement reset its attributes (here text color paint and fontSize)

### ISSUE THREAD

**Issue by AlexisCnockaert** [pharo-graphics/Bloc#501]
Here's the code:

random := BlElement new 
	background: Color lightOrange ;
	size: 200@200.
elem := BlTextElement new.
elem text: '20'  asRopedText.
	elem text attributes:
		{ (BlTextForegroundAttribute paint: Color white) }.
elem text fontSize: 30.
random addChild: elem.
random addEventHandlerOn: BlMouseDownEvent  do: [ :e |
	random childrenDo: [ :c |
		c text: 'new' asRopedText  ] ].
random openInNewSpace 

<img width="220" alt="Capture d’écran 2024-04-29 à 15 27 04" src="https://github.com/pharo-graphics/Bloc/assets/156106880/a80e09cb-f9e4-413b-bbdb-f2afe7f982c3">
<img width="220" alt="Capture d’écran 2024-04-29 à 15 27 10" src="https://github.com/pharo-graphics/Bloc/assets/156106880/b92638f3-b74a-47a7-b367-23d23ee3b7ff">

**Comment by tinchodias** [comment]
Reformatted:
```smalltalk
random := BlElement new
	          background: Color lightOrange;
	          size: 200 @ 200.
elem := BlTextElement new.
elem text: '20' asRopedText.
elem text attributes:
	{ (BlTextForegroundAttribute paint: Color white) }.
elem text fontSize: 30.
random addChild: elem.
random
	addEventHandlerOn: BlMouseDownEvent
	do: [ :e | random childrenDo: [ :c | c text: 'new' asRopedText ] ].
random openInNewSpace
```

**Comment by tinchodias** [comment]
This happens because the attributes belong to the `BlText`, not to the `BlTextElement`. I'm sorry but I will close the issue. Don't hesitate to continue the discussion if you consider.
