### ISSUE TITLE
Fix 4 tests on Pharo 13

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Bloc#550]
Errors from CI:

```
#########################
# 4 tests did not pass: #
#########################

BlDemoBasicNodeTest
 ✗ #testOnePackageWithTwoClassesHasTwoNodesWithSample2 (2ms)
UndeclaredVariableRead: Attempt to read undeclared variable RPackageOrganizer
UndeclaredVariable>>runtimeUndeclaredReadInContext:
BlDemoBasicNodeTest>>testOnePackageWithTwoClassesHasTwoNodesWithSample2 ...RPackageOrganizer
BlDemoBasicNodeTest(TestCase)>>performTest
 ✗ #testOnePackageWithTwoClassesHasTwoNodes (2ms)
UndeclaredVariableRead: Attempt to read undeclared variable RPackageOrganizer
UndeclaredVariable>>runtimeUndeclaredReadInContext:
BlDemoBasicNodeTest>>testOnePackageWithTwoClassesHasTwoNodes ...RPackageOrganizer
BlDemoBasicNodeTest(TestCase)>>performTest

BlRopedTextTest2
 ✗ #testInsertEmptyStrings (5ms)
Instance of BlTextAnnouncer did not understand #when:do:
BlTextAnnouncer(Object)>>doesNotUnderstand: #when:do:
BlRopedText(BlText)>>when:do:
BlRopedTextTest2>>testInsertEmptyStrings ...when: BlTextStringsInserted
		do: [ :anAnnouncement | insertedStrings := anAnnouncement strings ]
BlRopedTextTest2(TestCase)>>performTest
 ✗ #testAppendEmptyText (1ms)
Instance of BlTextAnnouncer did not understand #when:do:
BlTextAnnouncer(Object)>>doesNotUnderstand: #when:do:
BlRopedText(BlText)>>when:do:
BlRopedTextTest2>>testAppendEmptyText ...when: BlTextStringsInserted
		do: [ wasAnnounced := wasAnnounced + 1 ]
BlRopedTextTest2(TestCase)>>performTest
```

**Comment by tinchodias** [comment]
I'm looking for the equivalent in P13 of `(RPackageOrganizer default packageNamed: #'Bloc-Demo')` to fix 2 tests in `BlDemoBasicNodeTest`.

@jecisc do you know?

**Comment by tinchodias** [comment]
Another occurrence:
```
BlDemoPresenter>>
packagesToCollect
	^ RPackageOrganizer default packages select: [ :each |
		  each name includesSubstring: 'Bloc' ]
```

**Comment by jecisc** [comment]
You can access the package organizer of a class through #packageOrganizer method now :) Instead of referencing a global

**Comment by jecisc** [comment]
If your project need to also work in P11 you can take a look at this project: https://github.com/jecisc/PharoBackwardCompatibility

**Comment by jecisc** [comment]
> Another occurrence:
> 
> ```
> BlDemoPresenter>>
> packagesToCollect
> 	^ RPackageOrganizer default packages select: [ :each |
> 		  each name includesSubstring: 'Bloc' ]
> ```

This can become 

```st
BlDemoPresenter>>packagesToCollect
	^ self packageOrganizer packages select: [ :package | package name includesSubstring: 'Bloc' ]
```

**Comment by tinchodias** [comment]
Thanks @jecisc !
Yes, I like the deprecation and new way to to it. To make it work from p11 to p13, I'm replacing by `self class packageOrganizer`. Because `packageOrganizer` doesn't belong to Object in P11 but it does in ClassDescription

**Comment by jecisc** [comment]
It's also another possibility. 

If there are more cases you can check my PharoBackwardCompatibility project and I can add more API to it.

The idea is to add in older Pharo versions, API from newer versions. Like this, we can use the new API without worrying that older versions will not know them.

**Comment by tinchodias** [comment]
The remaining tests are what is reported in #433
