### ISSUE TITLE
Does BlLineGeometry works ?

### ISSUE THREAD

**Issue by Nyan11** [pharo-graphics/Bloc#570]
Hello, i was trying to use BlLineGeometry and i did not manage to make it work.

```st
lineElement := BlElement new
		  geometry: (BlLineGeometry from: 0 @ 0 to: 50 @ 50);
		  background: Color red;
		  border: (BlBorder paint: Color black width: 5);
		  size: 50 @ 50;
		  yourself.

lineElement openInSpace
```

![image](https://github.com/user-attachments/assets/691f0a49-a7bf-4e66-82f1-4a5a38dd8be8)

informations:
Pharo 11.0.0
Build information: Pharo-11.0.0+build.726.sha.aece1b5473acf3830a0e082c1bc3a15d4ff3522b (64 Bit)

bloc commit: a5fe2d3cbb74fb5d01f472191d61f0637ddf939a (2024-07-27)

**Comment by Nyan11** [comment]
I have the same result with Pharo 12

**Comment by tinchodias** [comment]
Hello @Nyan11 it's tricky: you need to set outskirts centered to the element. It can be done with `beOutskirtsCentered`. In the example:

```
lineElement := BlElement new
		  geometry: (BlLineGeometry from: 0 @ 0 to: 50 @ 50);

		  beOutskirtsCentered;  "<----"

		  background: Color red;
		  border: (BlBorder paint: Color black width: 5);
		  size: 50 @ 50;
		  yourself.

lineElement openInSpace
```
<img width="95" alt="Screenshot 2024-08-03 at 21 52 14" src="https://github.com/user-attachments/assets/e27277af-db6c-44bc-a713-ab9c8e3b9a07">

**Comment by tinchodias** [comment]
BTW, I also had this problem. I consider this a failure of the model. For geometries that are open paths, the outskirts don't make sense.

**Comment by tinchodias** [comment]
I'm closing it as question is responded. Let's reopen if you have some idea to discuss, or to create a PR to fix or workaround it.

**Comment by tinchodias** [comment]
@rvillemeur had a good idea to fix this confusing behavior: make open geometries such as line and polyline ignore the outskirts!

**Comment by Nyan11** [comment]
Hello,
I have two questions about the proposed fix:
- How do we change the thickness of the line ?
- Is it confusing to have two different behaviors for Polyline and Polygone ?

**Comment by labordep** [comment]
I agree. 
For open shapes (like lines or paths that do not close), the concept of a border being 'inside' or 'outside' becomes ambiguous: how to determine the direction for stroke alignment is unclear. There is no defined surface inside or outside of an open line. Center (the default behavior) makes the most sense: the stroke is centered on the line. In my opinion, this property is not at the right level in the Bloc API. It should be applied to the borders, and then it's up to the geometry to take it into account or not, if we follow this principle.

**Comment by rvillemeur** [comment]
It could be that way. BlCircleGeometry, BlRectangleGeometry and BlRoundedRectangle geometry have specific method to optimize with inside or outside outskirts (`aeApplyWithOutsideBorderTo: element: borderWidth:` and `aeApplyWithInsideBorderTo: element: borderWidth:`) These method are the only one using `AeCanvas >> borderPathFactory:` (c.f. recent email from Martin on the why behind it)  All other geometry rely on default painting behavior . Current fix use the same trick to force drawing line and one could implement this logic to all other closed geometry (triangle, square, ellipse)
