### ISSUE TITLE
 BlText>>#when:do: uses deprecated method

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#586]
Automatic deprecation code rewrite: The method Announcer>>#when:do: called from BlText>>#when:do: has been deprecated. Since there are some block closures (Clean and Constant) without a receiver, the API of announcements was changed to send the subscriber explicitly. 
			We are deprecating this method because it was asking for the receiver of the block to use it as the subscriber.

**Comment by tinchodias** [comment]
Thanks for the explanation. I'm closing it as this is duplicated with #433. I'm looking for a solution as it directly signals DNU in P13.
