### ISSUE TITLE
Remove = from Geometry

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#587]
following the discussion in 

https://github.com/pharo-graphics/Bloc/pull/558

we suggest to remove the = redefinition in geometry.

**Comment by tinchodias** [comment]
To take into account:
- #558 was in layout hierarchy
- Layout equals is used in `BlElement>>layout:` to avoid requesting layout if it didn't change
- I guess the screen capture showing a v11.0.0 release was added by mistake

**Comment by Ducasse** [comment]
Thanks for the feedback so may be we should not remove =
