### ISSUE TITLE
sendTo: methods are full of broken code....

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#590]
Check the implementors of sendTo: and see all the dead code.

**Comment by tinchodias** [comment]
@Ducasse, I browsed implementors of `sendTo:` and filtered "bloc" on the list, and only see `BlMousePickOutsideEvent>>#sendTo:` in red:

<img width="923" alt="Screenshot 2024-10-17 at 12 39 02" src="https://github.com/user-attachments/assets/deee2f4b-5ab7-459d-bfdc-3e38778071fd">

Maybe I fixed some of them in a recent PR.
