### ISSUE TITLE
25min SMALLTALK_CI_TIMEOUT?

### ISSUE THREAD

**Issue by fniephaus** [pharo-graphics/Bloc#6]
Hi @syrel,

When looking for the reason why coverage testing wasn't working, I noticed that [this project sets `$SMALLTALK_CI_TIMEOUT` to 25 minutes](https://github.com/pharo-graphics/Bloc/blob/d9dc027556451a18bbbe0a4a430cbc85a506e284/.travis.yml#L14). What's the reasoning behind this? It looks like [CI builds take less than 3 minutes](https://travis-ci.org/pharo-graphics/Bloc/builds/177336664), no need to increase the timeout, right?

**Comment by GlennCavarle** [comment]
Hi @fniephaus and thanks,
SMALLTALK_CI_TIMEOUT was used to try to solve an issue with win & mac jobs.
In the end, it was a problem with dependencies so, no need to increase the timeout.

**Comment by fniephaus** [comment]
Ah, cool. And please let me know if you have any ideas how to make smalltalkCI better 😃
