### ISSUE TITLE
Loading in Pharo 13 = CodeError

### ISSUE THREAD

**Issue by hernanmd** [pharo-graphics/Bloc#608]
There is a menu item in Pharo 13 to install the Baseline, Library -> "Load Toplo and Bloc". But it raises the following error:

<img width="1313" alt="Screenshot 2024-09-26 at 10 46 55" src="https://github.com/user-attachments/assets/80d97f9e-25f4-43b7-bad8-df8ce26f8cdd">

**Comment by tinchodias** [comment]
I did reproduce the issue locally. And checked that P12 doesn't have it. Thanks for reporting, I'm on it.

**Comment by tinchodias** [comment]
I moved the Pharo12 branch of Toplo to latest release this week, v0.2.0, and it works in both Pharo 12 and 13. Loading:

<img width="507" alt="Screenshot 2024-09-26 at 21 47 49" src="https://github.com/user-attachments/assets/8c2fc434-6bd2-47d2-a0e1-e2e13d59cad7">

It should be okay.

**Comment by tinchodias** [comment]
Before, Toplo:Pharo12 was loading Pharo12 branches on all dependencies too (Album, Bloc and Alexandrie). But I think that is not necessary, and it's fine to load detached versions of dependencies.
