### ISSUE TITLE
Fails to install on Pharo 8.0, Linux 64-bit

### ISSUE THREAD

**Issue by avasopht** [pharo-graphics/Bloc#61]
During installation it first warns of a missing `Key` package, and later `BaselineOfBloc` fails on a missing `TKTProfile`.

I created my 64-bit Pharo 8.0 image with PharoLauncher.

I get the same issue with Pharo 9.0.

With Pharo 7.0 I get failures with SkiaCanvas not supporting the methods on every example I tried.

**Comment by archaeron** [comment]
Same on Windows Pharo 8.0, 64-bit
