### ISSUE TITLE
Dead code regarding drag and drop

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Bloc#610]
We have these classes, only "cancel" is referenced:
<img width="193" alt="Screenshot 2024-09-30 at 13 25 06" src="https://github.com/user-attachments/assets/1cf06450-8ebb-4723-8b15-b474f7f0943c">

they are the only sends of these `spaceDraw*` selectors, and the methods have "red" (undefined) methods:
<img width="651" alt="Screenshot 2024-09-30 at 13 25 45" src="https://github.com/user-attachments/assets/f04809f4-5d14-47f3-bf40-d4fcb2f003b5">

@rvillemeur and @Enzo-Demeulenaere  do you know about this? do we remove this code?

**Comment by rvillemeur** [comment]
@tinchodias, these event are used in the GToolkit version of Drag&Drop, where dragged element are managed at the space level. They may be removed in the future, once we clarify exactly which way we want to handle drag&drop in Pharo. Stay with low level space, or provide higher level API like GToolkit, or a mix between both. There are no clear answers for now.

**Comment by tinchodias** [comment]
Let's close this issue. I recently merged a PR from Enzo regarding this topic, and I see it's on development.
