### ISSUE TITLE
Why BlZoomableElement is in utilities - Zoomable

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#62]
While it is used by BlPannableElement.

**Comment by Ducasse** [comment]
We could move it close to BlElement.

**Comment by tinchodias** [comment]
There is no `BlZoomableElement` now. It smells to be renamed as `BlZoomableLayout`, in 'Bloc-Layout-Zoomable' category.

**Comment by tinchodias** [comment]
And there is no `BlPannableElement`

**Comment by tinchodias** [comment]
That should be enough reason to close this issue.
