### ISSUE TITLE
Do we want hosts and universe Beacon signals?

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Bloc#624]
These Beacon signals are only signaled (i.e. only referenced to emit an instance):
<img width="362" alt="Screenshot 2024-10-09 at 16 45 25" src="https://github.com/user-attachments/assets/2d0063c8-8e60-4659-adc2-e27a81a79135">

They allow a developer to turn on a Beacon logger and watch what happens under the hood.

I create this issue to discuss if either we start to use them to debug, or we remove them and just debug this code as with other projects.

IMHO, this code doesn't help: it makes Bloc a bit harder to comprehend, and just regular Pharo debugging and profiling tools and are enough to debug or understand what happens under the hood.

Reasons would be similar for deleting telemetry months ago: https://github.com/pharo-graphics/Bloc/pull/439

**Comment by tinchodias** [comment]
Note: without those signals, the BlParallelUniverse's id becomes not necessary.

**Comment by tinchodias** [comment]
@plantec @labordep do you agree on removing these classes?

**Comment by labordep** [comment]
@tinchodias I agree with you.

**Comment by plantec** [comment]
yes

**Comment by tinchodias** [comment]
BlParallelUniverse is so much simplified after removing the signal emitting!

**Comment by tinchodias** [comment]
Only one Beacon signal remains: `BlParallelUniverseErrorDuringPulseSignal` (the Signal suffix was missing and I added it)

**Comment by tinchodias** [comment]
In part, I had the idea to remove the signals because they were quite 1:1 with BlSpaceEvent*s. I mean, handling events looked enough to generate a log, and also events are more oriented to react via handlers as a user software.

In that sense, BlParallelUniverseErrorDuringPulseSignal may be replaced by a new BlParallelUniversePulseErrorEvent.

**Comment by labordep** [comment]
hi @tinchodias, with @Nyan11 we for doing stuff when a space is open with Pyramid (to install a keyboard shortcut to edit it), what event can we used?

**Comment by tinchodias** [comment]
For the record:
```smalltalk
"Start logger"
logger := MemoryLogger new.
logger startFor: BlParallelUniverseErrorDuringPulseSignal.
logger isRunning. "true"

"Generate an error"
[
[ 1 / 0 ]
	on: Exception
	do: [ :e |
			(BlParallelUniverseErrorDuringPulseSignal new
				 signaledError: e;
				 yourself) emit ]
] fork.

"After a wait, check it is logged:"
logger entries size. 

"Tear down"
logger reset.
logger stop.
```
