### ISSUE TITLE
BlSpaceManager is only a collection of BlSpace for BlParallelUniverses

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Bloc#637]
`BlSpaceManager` is an ad-hoc Set (or `OrderedCollection` without repeated items) that is only referenced from `BlParallelUniverse`. 

I propose to delete `BlSpaceManager` and use a `Set` from `BlParallelUniverse`. Or some variant of this,

**Comment by labordep** [comment]
@tinchodias BlSpaceManager cannot be used to manage some desktop application windows? It is similar to workspace management?

**Comment by tinchodias** [comment]
No! the manager is mainly add, remove and do with some particularities
