### ISSUE TITLE
Error throwed when stoppping animation

### ISSUE THREAD

**Issue by ELePors** [pharo-graphics/Bloc#638]
There is an unnecessary error thrown by BlBaseAnimation where a log is more precious.
in multi-threaded context, an animation can be stop asyncronously by other elements, an if i stop a BlAnimation which is not running, i get an error which opens a debugger.
When you stop a running task, it stops... when it is not running ... do nothing... it will be stopped 

Thanks
Eric

**Comment by labordep** [comment]
@tinchodias @tesonep @plantec what is your opinion?
We are thinking it is a source of errors to put the responsibility on the user to control animation's states.
User need to do "play" or "stop" and Bloc should be control states internaly.
Thanks :)

**Comment by tinchodias** [comment]
This is the annoying error in `BlBaseAnimation`, right?
```smalltalk
start

	isRunning ifTrue: [
		self error: 'Animation can not be start multiple times without stop' ].

	self initStart
```

**Comment by labordep** [comment]
Thanks @tinchodias!
