### ISSUE TITLE
No need to have id in BlSpace, BlTask and BlParallelUniverse

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Bloc#639]
Instances of `BlSpace`, `BlTask` and `BlParallelUniverse` are initialized like this:

```smalltalk
initialize
	super initialize.
	id := UniqueIdGenerator generateUniqueId.
```

where this id is an integer and the generator is initialized on class-side, like:

```smalltalk
initialize
	UniqueIdGenerator := BlUniqueIdGenerator new
```

(each of the 3 classes has it's own generator).

I propose to remove this, as it mostly adds noise to the code. Pharo and Smalltalk objects have identityHash and this should be more than enough for a developer to identify instances while debugging, reading logs, etc.

**Comment by tinchodias** [comment]
Related:
- `BlSpace class>>#spaceWithId:do:` has no senders
- Bloc Beacon signals are the main users of ids (See #624)

**Comment by tinchodias** [comment]
@plantec @labordep I'm not talking of removing BlElement's ids. I think element id makes sense, and I think they are used in Toplo and Stylesheets. But what's your opinion on ids on BlSpace, BlTask and BlParallelUniverse?

**Comment by labordep** [comment]
Hi @tinchodias, I agree with you :-) I use it to identify an instance during debug but if the hash is working this is the same thing.
