### ISSUE TITLE
BlScrollFlinger refers to BlQuinticInterpolator

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#64]
defaultInterpolator
	^ BlQuinticInterpolator default

**Comment by tinchodias** [comment]
Now, there is no `BlScrollFlinger` class.
`BlQuinticInterpolator` is in 'Bloc-Basic-Interpolators' category.
In my image with NewBloc + Memory, it is only referenced from this method in `MGCardElement`:

```
onFlippedFace
	| animation |

	animation := BlTransformAnimation scale: 0.85 @ 0.85.	
	animation
		absolute;
		easing: BlQuinticInterpolator default;
		duration: 0.3 seconds.
	
	self addAnimation: animation.
```

**Comment by tinchodias** [comment]
I don't find a `defaultInterpolator`, also.
Enough reasons to close this issue.
