### ISSUE TITLE
BlSpace has 2 candidates to be removed

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Bloc#640]
These two methods have no senders and have been marked with this protocol:

<img width="685" alt="Screenshot 2024-10-23 at 13 06 50" src="https://github.com/user-attachments/assets/895919f8-b22a-4328-ae2f-70215862119b">

@plantec marked it 1 year ago:

<img width="848" alt="Screenshot 2024-10-23 at 13 11 01" src="https://github.com/user-attachments/assets/873938ef-9e39-45c0-a237-023d66f9d3ef">

Normally we deprecate them first. Or manybe in this case we just remove them.

**Comment by labordep** [comment]
Seems OK for me. You can remove them directly.
