### ISSUE TITLE
Do not use Array2D

### ISSUE THREAD

**Issue by XDracam** [pharo-graphics/Bloc#643]
When trying to open `testElementWithLinearTranslationAnimation` (and the other two related examples) in the Bloc UI Framework Demo, I get an error that the `Array2D` class does not exist anymore in Pharo 13. And indeed, this class has been deprecated in previous Pharo versions.

![image](https://github.com/user-attachments/assets/cd0cabdc-0d98-4b62-ae53-953769e492f1)

**Comment by tinchodias** [comment]
Hello @XDracam I don't find this version of `testElementWithLinearTranslationAnimation`. What tag of branch did you load?

In the Bloc:dev in my image, it looks like this:
```
testElementWithLinearTranslationAnimation
	<sampleInstance>
	<demo>
	| container element animation |
	animation := self linearTranslationAnimation.
	element := self animationElement.
	element position: 5 @ 5.
	container := self containerElement.
	container addChild: element.
	element addAnimation: animation.
	^ container
```
and it belongs to `BlTransformationAnimationTest` class.

I picked v1.0.0 to see it that's your version but I also didn't find it. So, I ask you.

**Comment by lugu** [comment]
Same issue with `BlMatrix2D>>decomposition`, since https://github.com/pharo-project/pharo/commit/ba608f9bb8962e5576ba574a4c2d762623b94f47 Array2D isn't part of the base pharo image (pharo 13) as per https://github.com/pharo-project/pharo/issues/12140.

**Comment by tinchodias** [comment]
okay. these are the references in bloc:dev to Array2D:
<img width="309" alt="Screenshot 2024-11-11 at 23 10 25" src="https://github.com/user-attachments/assets/9abd9ce3-8c2b-498f-b666-15bf35baeba3">

**Comment by tinchodias** [comment]
@lugu any suggestion on the replacement? in Roassal, I see it was replaced by a simple Dictionary: https://github.com/pharo-graphics/Roassal/commit/8394f6f0b053d7ec60fcdf7a8a9bbd896706bb4f

**Comment by tinchodias** [comment]
* `asMatrixCollection` was only used from `printOn:`. I rewrote it to print directly.
* The real use was as internal state of `BlMatrixDecomposition2D`, to store (sx, sy, shx, shy) values in some maths for interpolation. I rewrote the code to directly reference those 4 values instead of the `Array2D`.

**Comment by VanKichline** [comment]
Pharo by Example chapter 6 relies on Array2D for the Lights Out walkthrough.
This is the currently recommended means of learning Pharo for the beginner.
