### ISSUE TITLE
Is BlBitFlags used

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#67]

**Comment by tinchodias** [comment]
Not direct references, but it has subclasses that are referenced and clearly very used.

```
BlBitflags allSubclasses 
>>> an OrderedCollection(BlBoundsMatcherConstraints BlElementEventDispatcherActivatedEvents BlElementFlags) 
```

The last 2 of them are instantiated in BlElement>>initialize, assigned to instance variables and used a lot.

**Comment by tinchodias** [comment]
(See #84)

**Comment by Ducasse** [comment]
Yes now I would like marcus to look at them because they are a bit too magic and turned them into Slots.
