### ISSUE TITLE
DNU BlSpace >> withHalos

### ISSUE THREAD

**Issue by plantec** [pharo-graphics/Bloc#69]
fresh Pharo 9 image
loaded BlocCore (default) baseline from Iceberg

space := BlSpace new.
space addChild: BlElement new.
space show

**Comment by tinchodias** [comment]
The snippet doesn't signal DNU now. It works.

And `BlSpace >> withHalos` doesn't exist, BTW... maybe it should exist.

**Comment by tinchodias** [comment]
I mean... we may want halos and I saw them in an old Bloc demo from 2014: https://vimeo.com/115336678 

I just searched in the history of this repository for something like "withHalos" or only files containing the word "halo" but didn't get anything.

But when I navigated back until the first commits, I see they were in November 2016, migrated from other repository. 

Could you confirm me if it's true that halos existed and were removed before 2016?

**Comment by plantec** [comment]
Hello,
yes they was implemented in the first version. removed after. 
We should rethink about their integration. The idea was to have them in a separate
 package so that we could remove them as we can do for tests or examples.
