### ISSUE TITLE
OSWIndowHandle has been renamed in Pharo 90

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#71]
In Pharo 80 with Bloc (and not Bloc-Core).

![Capture_decran_2020-10-13_a_18 26 47](https://user-images.githubusercontent.com/432549/95954242-46c1f200-0dfb-11eb-9070-2c5c1cfa12b2.png)

**Comment by tinchodias** [comment]
This was fixed, right?

**Comment by Ducasse** [comment]
Yes
