### ISSUE TITLE
Loading Bloc Core + Sparta + Morphic => too many depend project loaded

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#75]
```
Metacello new
    baseline: 'BlocCore';
    repository: 'github://pharo-graphics/Bloc/src';
    load.
```

```
Metacello new
    baseline: 'BlocSparta';
    repository: 'github://pharo-graphics/Bloc/src';
    load.
```

```
Metacello new
    baseline: 'BlocMorphic';
    repository: 'github://pharo-graphics/Bloc/src';
    load.
```

![Screenshot 2021-02-08 at 20 06 51](https://user-images.githubusercontent.com/432549/107269065-52d85c00-6a49-11eb-881a-a425c7228b8b.png)

**Comment by Ducasse** [comment]
Here is the baseline of BlocCore

```
baseline: spec
	<baseline>
	spec for: #'common' do: [
		spec 
			baseline: 'Beacon' with: [
				spec repository: 'github://feenkcom/pharo-beacon/repository' ];
			baseline: 'Fenster' with: [
				spec repository: 'github://feenkcom/fenster/src' ].
		spec 
			package: #Bloc with: [
				spec requires: #(#Beacon Fenster) ];
			package: #'BlocHost-Mock' with: [
				spec requires: #(#Bloc ). ];
			package: #'Bloc-Tests' with: [
				spec requires: #(#Bloc 'BlocHost-Mock' ). ]. ].
```

**Comment by Ducasse** [comment]
Fenster should be copied back to Bloc

**Comment by Ducasse** [comment]
Here is the baselineOfBlocMorphic
```
baseline: spec
	<baseline>
	spec for: #'common' do: [
		spec 
			baseline: 'BlocCore' with: [
				spec repository: 'github://feenkcom/Bloc/src' ];
			baseline: 'Fenster' with: [
				spec repository: 'github://feenkcom/fenster/src' ].

		spec 
			package: #'BlocHost-Morphic' with: [
				spec requires: #(#BlocCore #Fenster) ] ].
```

**Comment by Ducasse** [comment]
Here is the one of Bloc-Sparta

```
baseline: spec
	<baseline>
	spec for: #'common' do: [
		spec 
			baseline: 'Sparta' with: [
				spec repository: 'github://feenkcom/Sparta/src' ];
			baseline: 'BlocCore' with: [
				spec repository: 'github://feenkcom/Bloc/src' ];
			baseline: 'BlocText' with: [
				spec repository: 'github://feenkcom/Bloc/src' ].

		spec
			package: #'Bloc-Compositor' with: [
				spec requires: #('BlocCore' 'Sparta'). ].
			
		spec
			package: #'Bloc-Sparta' with: [
				spec requires: #('Sparta' 'BlocCore' 'BlocText' 'Bloc-Compositor'). ] ].
```

**Comment by Ducasse** [comment]
We should not have reference to feenk repo.

**Comment by tinchodias** [comment]
Minutes ago I pushed a change of all feenkcom/Bloc to pharo-graphics/Bloc.

Didn't touch for other repositories e.g. Sparta.

**Comment by tinchodias** [comment]
Fenster should be a package in Bloc repo?

**Comment by tinchodias** [comment]
Additionally, I wonder whether Beacon can be easily replaced with the one in the image or not.

**Comment by syrel** [comment]
The reason why Fenster is in a separate repository is because it is used by windowing libraries such as `Glutin` which is packaged outside of bloc.

So we have now the following dependencies between **repositories**:

```
Bloc (pharo-graphics)
      --> Fenster (fenster)
      --> Glutin (glutin)
           --> Fenster (fenster)
```

if we move Fenster to `pharo-graphics` then there will be a circluar dependency between **repositories**::
```
Bloc
   --> Fenster
   --> Glutin
     ---> Fenster
           ---> Bloc
```
Circluar deopendencies between repositiories is not possible to handle when creating a reproducible release baselines due to commit tags

Maybe it would be better to consider using polymorphism and get rid of fenster completely?
Although it may require copy-pasting some logic for transforming between logical and physical window coordinates (extent and position)

**Comment by tinchodias** [comment]
@syrel I'd like to know more of the polymorphism alternative to rid of fenster. I didn't get it.

**Comment by syrel** [comment]
Never mind, moving fenster to bloc is a solution

**Comment by Ducasse** [comment]
Fenster is easy and small. It is not really important.

**Comment by tinchodias** [comment]
It's now Bloc-Display.
