### ISSUE TITLE
Loading BlCore, BlTransformationExamples>>openInWindow:named:extent: fails

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#77]
```
openInWindow: anElement named: aTitleString extent: aPoint
	"Open a given element in a window of a provided extent and specified title"
	| aSpace |
	aSpace := BlSpace new
		extent: aPoint;
		title: aTitleString.
	
	aSpace root background: self spaceBackground.
	aSpace root addChild: anElement.

	aSpace root addEventHandler:
			(BlEventHandler
				on: BlDoubleClickEvent
				do: [ :evt | BlElementSelection on: evt target ]).
	
	aSpace show
```
Because BlElementSelection is unknown

**Comment by tinchodias** [comment]
By a full string search in a text editor, I see that BlElementSelection belongs to category 'Bloc-DevTool-Core'.

**Comment by tinchodias** [comment]
This `openInWindow:named:extent:` method is defined in `TBlExample`, which is not loaded by NewBloc.

**Comment by tinchodias** [comment]
Now I found that still `BlFlowLayoutCompositionExamples class>>#floatingCells` and `BlFlowLayoutCompositionSmokeTest class>>#floatingCells` reference `BlElementSelection`.

So I reopen.

**Comment by Ducasse** [comment]
I do not see any users of TBlExample.
We will have to check what is Bloc-DevTool-Core.

**Comment by tinchodias** [comment]
In v2.0.0, BlElementSelection is loaded. In the other hand, BlTransformationExamples was renamed as BlAnimationExamplesTest. Looking at this issue again made me improve the code.

**Comment by tinchodias** [comment]
I close it, after https://github.com/pharo-graphics/Bloc/commit/2a16d0510fbb631eead4ffefdd64aa0bb19cbe9e
