### ISSUE TITLE
Layout depends on animation mainly because 

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#88]
```
BlZoomableLayoutElementAction >> measured: aChildNode element: anElement
	aChildNode constraints zoomable isDirty
		ifTrue: [
			animationDuration isZero
				ifTrue: [ anElement transformDo: [ :t | t scaleBy: aChildNode constraints zoomable scaleFactor ] ]
				ifFalse: [ anElement addAnimation: ((BlTransformAnimation scale: aChildNode constraints zoomable scaleFactor) absolute duration: self animationDuration) ] ].
	aChildNode constraints zoomable isDirty: false
```

**Comment by Ducasse** [comment]
So it can be packaged in a separate package.

**Comment by tinchodias** [comment]
I will take a look. 
From the names in the snippet, I imagine it's an animation that smooths the zoom-in or -out. 
And wonder if it can be rewritten to a less cool version that doesn't have animation.

**Comment by syrel** [comment]
I don’t think it should be in Bloc. We will package it in a separate repo

**Comment by Ducasse** [comment]
You see I was about to split the package and have AnimatedLayout. 
For me this is ok to have it in bloc but I want to control dependency. 
So let me know.
