### ISSUE TITLE
BaselineOfBlocAnimation is not necessary

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#91]
```
baseline: spec
	<baseline>
	spec for: #'common' do: [
		spec 
			baseline: 'BlocCore' with: [
				spec repository: 'github://pharo-graphics/Bloc/src' ].
		spec 
			package: #'Bloc-Animation' with: [
				spec requires: #(#BlocCore ). ] ].
```

**Comment by tinchodias** [comment]
There is a "Bloc-Animation-Tests" package that is ignored by this baseline. And it is also ignored by `BaselineOfBloc`, which is a flattened version of several baselines in this repository.

@Ducasse what do you propose, to remove this baseline?

`BaselineOfNewBloc` uses `BlocLayout`, which uses `BaselineOfBlocAnimation`.

**Comment by Ducasse** [comment]
I do not know :)
I would remove it to reduce the cognitive load.

**Comment by tinchodias** [comment]
This baseline was removed time ago
