### ISSUE TITLE
Why fenster does not extend point

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#95]
This way we could create instances of Size and Position without having to explicitly refers to the classes.

**Comment by syrel** [comment]
Extending point is not possible because Point is orthogonal to the Size. Maybe having Size and Position in the core of pharo would make it clearer

**Comment by Ducasse** [comment]
I was unclear.  Why logicalSize has a  fromPoint:?
What I meant is that it would be better to have 

```
aPoint asLogicalPosition 
aPoint asLogicalSize
```
than writing 

```
FensterLogicalPosition fromPoint: aPoint
FensterLogicalSize fromPoint: aPoint
```
Because my solution encapsulate better and avoid the spread of FensterLogicalPosition and FensterLogicalSize

**Comment by syrel** [comment]
Yes 👍

**Comment by Ducasse** [comment]
Do you want me to give a try?

**Comment by Ducasse** [comment]
Now even in Pharo I limit my use of direct class references.

**Comment by syrel** [comment]
Limiting direct class references is a good idea 💡

**Comment by Ducasse** [comment]
asLogical and friends got introduced. Next step using them.

**Comment by tinchodias** [comment]
I did a pass on code loaded by BaselineOfNewBloc. Did 2 commits:

- FensterLogicalPosition -> 0 occurrences
- FensterLogicalSize -> 5 occurrences in commit 08eb6feb65c10e6aba4e123faba368483706e8b6
- FensterPhysicalPosition -> 0 occurrences
- FensterPhysicalSize -> 1 occurrence in commit 9d04216e81a200ac039f556d990efad46e3c2e2d

**Comment by tinchodias** [comment]
So, no more direct references to those 4 classes (I mean, outside Fenster)
